/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.AccessAclGetAclResponse
import com.clientapi.pbs.models.AccessAclUpdateAclRequest
import com.clientapi.pbs.models.AccessAclUpdateAclResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class AccessAclApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * GET /access/acl
     * Read Access Control List (ACLs)
     * Read Access Control List (ACLs).  Permissions: Returns all ACLs if user has Sys.Audit on &#39;/access/acl&#39;, or just the ACLs containing the user&#39;s API tokens.
     * @param exact If set, returns only ACL for the exact path. (optional, default to false)
     * @param path Access control path. (optional)
     * @return AccessAclGetAclResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessAclGetAcl(exact: kotlin.Boolean? = false, path: kotlin.String? = null) : AccessAclGetAclResponse {
        val localVarResponse = accessAclGetAclWithHttpInfo(exact = exact, path = path)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessAclGetAclResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /access/acl
     * Read Access Control List (ACLs)
     * Read Access Control List (ACLs).  Permissions: Returns all ACLs if user has Sys.Audit on &#39;/access/acl&#39;, or just the ACLs containing the user&#39;s API tokens.
     * @param exact If set, returns only ACL for the exact path. (optional, default to false)
     * @param path Access control path. (optional)
     * @return ApiResponse<AccessAclGetAclResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessAclGetAclWithHttpInfo(exact: kotlin.Boolean?, path: kotlin.String?) : ApiResponse<AccessAclGetAclResponse?> {
        val localVariableConfig = accessAclGetAclRequestConfig(exact = exact, path = path)

        return request<Unit, AccessAclGetAclResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessAclGetAcl
     *
     * @param exact If set, returns only ACL for the exact path. (optional, default to false)
     * @param path Access control path. (optional)
     * @return RequestConfig
     */
    fun accessAclGetAclRequestConfig(exact: kotlin.Boolean?, path: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (exact != null) {
                    put("exact", listOf(exact.toString()))
                }
                if (path != null) {
                    put("path", listOf(path.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/access/acl",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /access/acl
     * Update Access Control List (ACLs)
     * Update Access Control List (ACLs).  Permissions: Requires Permissions.Modify on &#39;/access/acl&#39;, limited to updating ACLs of the user&#39;s API tokens otherwise.
     * @param accessAclUpdateAclRequest 
     * @return AccessAclUpdateAclResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun accessAclUpdateAcl(accessAclUpdateAclRequest: AccessAclUpdateAclRequest) : AccessAclUpdateAclResponse {
        val localVarResponse = accessAclUpdateAclWithHttpInfo(accessAclUpdateAclRequest = accessAclUpdateAclRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AccessAclUpdateAclResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /access/acl
     * Update Access Control List (ACLs)
     * Update Access Control List (ACLs).  Permissions: Requires Permissions.Modify on &#39;/access/acl&#39;, limited to updating ACLs of the user&#39;s API tokens otherwise.
     * @param accessAclUpdateAclRequest 
     * @return ApiResponse<AccessAclUpdateAclResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun accessAclUpdateAclWithHttpInfo(accessAclUpdateAclRequest: AccessAclUpdateAclRequest) : ApiResponse<AccessAclUpdateAclResponse?> {
        val localVariableConfig = accessAclUpdateAclRequestConfig(accessAclUpdateAclRequest = accessAclUpdateAclRequest)

        return request<AccessAclUpdateAclRequest, AccessAclUpdateAclResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation accessAclUpdateAcl
     *
     * @param accessAclUpdateAclRequest 
     * @return RequestConfig
     */
    fun accessAclUpdateAclRequestConfig(accessAclUpdateAclRequest: AccessAclUpdateAclRequest) : RequestConfig<AccessAclUpdateAclRequest> {
        val localVariableBody = accessAclUpdateAclRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/access/acl",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
