/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.BackupUpgradeCreateBlobRequest
import com.clientapi.pbs.models.BackupUpgradeCreateBlobResponse
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicChunkRequest
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicChunkResponse
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicCloseRequest
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicCloseResponse
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicIndexRequest
import com.clientapi.pbs.models.BackupUpgradeCreateDynamicIndexResponse
import com.clientapi.pbs.models.BackupUpgradeCreateFinishResponse
import com.clientapi.pbs.models.BackupUpgradeCreateFixedChunkRequest
import com.clientapi.pbs.models.BackupUpgradeCreateFixedChunkResponse
import com.clientapi.pbs.models.BackupUpgradeCreateFixedCloseRequest
import com.clientapi.pbs.models.BackupUpgradeCreateFixedCloseResponse
import com.clientapi.pbs.models.BackupUpgradeCreateFixedIndexRequest
import com.clientapi.pbs.models.BackupUpgradeCreateFixedIndexResponse
import com.clientapi.pbs.models.BackupUpgradeCreateSpeedtestResponse
import com.clientapi.pbs.models.BackupUpgradeGetPreviousBackupTimeResponse
import com.clientapi.pbs.models.BackupUpgradeGetPreviousResponse
import com.clientapi.pbs.models.BackupUpgradeGetUpgradeResponse
import com.clientapi.pbs.models.BackupUpgradeUpdateDynamicIndexRequest
import com.clientapi.pbs.models.BackupUpgradeUpdateDynamicIndexResponse
import com.clientapi.pbs.models.BackupUpgradeUpdateFixedIndexRequest
import com.clientapi.pbs.models.BackupUpgradeUpdateFixedIndexResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class BackupUpgradeApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /backup/_upgrade_/blob
     * Upload binary blob file
     * Upload binary blob file.
     * @param backupUpgradeCreateBlobRequest 
     * @return BackupUpgradeCreateBlobResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateBlob(backupUpgradeCreateBlobRequest: BackupUpgradeCreateBlobRequest) : BackupUpgradeCreateBlobResponse {
        val localVarResponse = backupUpgradeCreateBlobWithHttpInfo(backupUpgradeCreateBlobRequest = backupUpgradeCreateBlobRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateBlobResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/blob
     * Upload binary blob file
     * Upload binary blob file.
     * @param backupUpgradeCreateBlobRequest 
     * @return ApiResponse<BackupUpgradeCreateBlobResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateBlobWithHttpInfo(backupUpgradeCreateBlobRequest: BackupUpgradeCreateBlobRequest) : ApiResponse<BackupUpgradeCreateBlobResponse?> {
        val localVariableConfig = backupUpgradeCreateBlobRequestConfig(backupUpgradeCreateBlobRequest = backupUpgradeCreateBlobRequest)

        return request<BackupUpgradeCreateBlobRequest, BackupUpgradeCreateBlobResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateBlob
     *
     * @param backupUpgradeCreateBlobRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateBlobRequestConfig(backupUpgradeCreateBlobRequest: BackupUpgradeCreateBlobRequest) : RequestConfig<BackupUpgradeCreateBlobRequest> {
        val localVariableBody = backupUpgradeCreateBlobRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/blob",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/dynamic_chunk
     * Upload a new chunk
     * Upload a new chunk.
     * @param backupUpgradeCreateDynamicChunkRequest 
     * @return BackupUpgradeCreateDynamicChunkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateDynamicChunk(backupUpgradeCreateDynamicChunkRequest: BackupUpgradeCreateDynamicChunkRequest) : BackupUpgradeCreateDynamicChunkResponse {
        val localVarResponse = backupUpgradeCreateDynamicChunkWithHttpInfo(backupUpgradeCreateDynamicChunkRequest = backupUpgradeCreateDynamicChunkRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateDynamicChunkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/dynamic_chunk
     * Upload a new chunk
     * Upload a new chunk.
     * @param backupUpgradeCreateDynamicChunkRequest 
     * @return ApiResponse<BackupUpgradeCreateDynamicChunkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateDynamicChunkWithHttpInfo(backupUpgradeCreateDynamicChunkRequest: BackupUpgradeCreateDynamicChunkRequest) : ApiResponse<BackupUpgradeCreateDynamicChunkResponse?> {
        val localVariableConfig = backupUpgradeCreateDynamicChunkRequestConfig(backupUpgradeCreateDynamicChunkRequest = backupUpgradeCreateDynamicChunkRequest)

        return request<BackupUpgradeCreateDynamicChunkRequest, BackupUpgradeCreateDynamicChunkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateDynamicChunk
     *
     * @param backupUpgradeCreateDynamicChunkRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateDynamicChunkRequestConfig(backupUpgradeCreateDynamicChunkRequest: BackupUpgradeCreateDynamicChunkRequest) : RequestConfig<BackupUpgradeCreateDynamicChunkRequest> {
        val localVariableBody = backupUpgradeCreateDynamicChunkRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/dynamic_chunk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/dynamic_close
     * Close dynamic index writer
     * Close dynamic index writer.
     * @param backupUpgradeCreateDynamicCloseRequest 
     * @return BackupUpgradeCreateDynamicCloseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateDynamicClose(backupUpgradeCreateDynamicCloseRequest: BackupUpgradeCreateDynamicCloseRequest) : BackupUpgradeCreateDynamicCloseResponse {
        val localVarResponse = backupUpgradeCreateDynamicCloseWithHttpInfo(backupUpgradeCreateDynamicCloseRequest = backupUpgradeCreateDynamicCloseRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateDynamicCloseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/dynamic_close
     * Close dynamic index writer
     * Close dynamic index writer.
     * @param backupUpgradeCreateDynamicCloseRequest 
     * @return ApiResponse<BackupUpgradeCreateDynamicCloseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateDynamicCloseWithHttpInfo(backupUpgradeCreateDynamicCloseRequest: BackupUpgradeCreateDynamicCloseRequest) : ApiResponse<BackupUpgradeCreateDynamicCloseResponse?> {
        val localVariableConfig = backupUpgradeCreateDynamicCloseRequestConfig(backupUpgradeCreateDynamicCloseRequest = backupUpgradeCreateDynamicCloseRequest)

        return request<BackupUpgradeCreateDynamicCloseRequest, BackupUpgradeCreateDynamicCloseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateDynamicClose
     *
     * @param backupUpgradeCreateDynamicCloseRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateDynamicCloseRequestConfig(backupUpgradeCreateDynamicCloseRequest: BackupUpgradeCreateDynamicCloseRequest) : RequestConfig<BackupUpgradeCreateDynamicCloseRequest> {
        val localVariableBody = backupUpgradeCreateDynamicCloseRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/dynamic_close",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/dynamic_index
     * Create dynamic chunk index file
     * Create dynamic chunk index file.
     * @param backupUpgradeCreateDynamicIndexRequest 
     * @return BackupUpgradeCreateDynamicIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateDynamicIndex(backupUpgradeCreateDynamicIndexRequest: BackupUpgradeCreateDynamicIndexRequest) : BackupUpgradeCreateDynamicIndexResponse {
        val localVarResponse = backupUpgradeCreateDynamicIndexWithHttpInfo(backupUpgradeCreateDynamicIndexRequest = backupUpgradeCreateDynamicIndexRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateDynamicIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/dynamic_index
     * Create dynamic chunk index file
     * Create dynamic chunk index file.
     * @param backupUpgradeCreateDynamicIndexRequest 
     * @return ApiResponse<BackupUpgradeCreateDynamicIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateDynamicIndexWithHttpInfo(backupUpgradeCreateDynamicIndexRequest: BackupUpgradeCreateDynamicIndexRequest) : ApiResponse<BackupUpgradeCreateDynamicIndexResponse?> {
        val localVariableConfig = backupUpgradeCreateDynamicIndexRequestConfig(backupUpgradeCreateDynamicIndexRequest = backupUpgradeCreateDynamicIndexRequest)

        return request<BackupUpgradeCreateDynamicIndexRequest, BackupUpgradeCreateDynamicIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateDynamicIndex
     *
     * @param backupUpgradeCreateDynamicIndexRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateDynamicIndexRequestConfig(backupUpgradeCreateDynamicIndexRequest: BackupUpgradeCreateDynamicIndexRequest) : RequestConfig<BackupUpgradeCreateDynamicIndexRequest> {
        val localVariableBody = backupUpgradeCreateDynamicIndexRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/dynamic_index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/finish
     * Mark backup as finished
     * Mark backup as finished.
     * @return BackupUpgradeCreateFinishResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateFinish() : BackupUpgradeCreateFinishResponse {
        val localVarResponse = backupUpgradeCreateFinishWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateFinishResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/finish
     * Mark backup as finished
     * Mark backup as finished.
     * @return ApiResponse<BackupUpgradeCreateFinishResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateFinishWithHttpInfo() : ApiResponse<BackupUpgradeCreateFinishResponse?> {
        val localVariableConfig = backupUpgradeCreateFinishRequestConfig()

        return request<Unit, BackupUpgradeCreateFinishResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateFinish
     *
     * @return RequestConfig
     */
    fun backupUpgradeCreateFinishRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/finish",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/fixed_chunk
     * Upload a new chunk
     * Upload a new chunk.
     * @param backupUpgradeCreateFixedChunkRequest 
     * @return BackupUpgradeCreateFixedChunkResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateFixedChunk(backupUpgradeCreateFixedChunkRequest: BackupUpgradeCreateFixedChunkRequest) : BackupUpgradeCreateFixedChunkResponse {
        val localVarResponse = backupUpgradeCreateFixedChunkWithHttpInfo(backupUpgradeCreateFixedChunkRequest = backupUpgradeCreateFixedChunkRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateFixedChunkResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/fixed_chunk
     * Upload a new chunk
     * Upload a new chunk.
     * @param backupUpgradeCreateFixedChunkRequest 
     * @return ApiResponse<BackupUpgradeCreateFixedChunkResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateFixedChunkWithHttpInfo(backupUpgradeCreateFixedChunkRequest: BackupUpgradeCreateFixedChunkRequest) : ApiResponse<BackupUpgradeCreateFixedChunkResponse?> {
        val localVariableConfig = backupUpgradeCreateFixedChunkRequestConfig(backupUpgradeCreateFixedChunkRequest = backupUpgradeCreateFixedChunkRequest)

        return request<BackupUpgradeCreateFixedChunkRequest, BackupUpgradeCreateFixedChunkResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateFixedChunk
     *
     * @param backupUpgradeCreateFixedChunkRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateFixedChunkRequestConfig(backupUpgradeCreateFixedChunkRequest: BackupUpgradeCreateFixedChunkRequest) : RequestConfig<BackupUpgradeCreateFixedChunkRequest> {
        val localVariableBody = backupUpgradeCreateFixedChunkRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/fixed_chunk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/fixed_close
     * Close fixed index writer
     * Close fixed index writer.
     * @param backupUpgradeCreateFixedCloseRequest 
     * @return BackupUpgradeCreateFixedCloseResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateFixedClose(backupUpgradeCreateFixedCloseRequest: BackupUpgradeCreateFixedCloseRequest) : BackupUpgradeCreateFixedCloseResponse {
        val localVarResponse = backupUpgradeCreateFixedCloseWithHttpInfo(backupUpgradeCreateFixedCloseRequest = backupUpgradeCreateFixedCloseRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateFixedCloseResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/fixed_close
     * Close fixed index writer
     * Close fixed index writer.
     * @param backupUpgradeCreateFixedCloseRequest 
     * @return ApiResponse<BackupUpgradeCreateFixedCloseResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateFixedCloseWithHttpInfo(backupUpgradeCreateFixedCloseRequest: BackupUpgradeCreateFixedCloseRequest) : ApiResponse<BackupUpgradeCreateFixedCloseResponse?> {
        val localVariableConfig = backupUpgradeCreateFixedCloseRequestConfig(backupUpgradeCreateFixedCloseRequest = backupUpgradeCreateFixedCloseRequest)

        return request<BackupUpgradeCreateFixedCloseRequest, BackupUpgradeCreateFixedCloseResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateFixedClose
     *
     * @param backupUpgradeCreateFixedCloseRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateFixedCloseRequestConfig(backupUpgradeCreateFixedCloseRequest: BackupUpgradeCreateFixedCloseRequest) : RequestConfig<BackupUpgradeCreateFixedCloseRequest> {
        val localVariableBody = backupUpgradeCreateFixedCloseRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/fixed_close",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/fixed_index
     * Create fixed chunk index file
     * Create fixed chunk index file.
     * @param backupUpgradeCreateFixedIndexRequest 
     * @return BackupUpgradeCreateFixedIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateFixedIndex(backupUpgradeCreateFixedIndexRequest: BackupUpgradeCreateFixedIndexRequest) : BackupUpgradeCreateFixedIndexResponse {
        val localVarResponse = backupUpgradeCreateFixedIndexWithHttpInfo(backupUpgradeCreateFixedIndexRequest = backupUpgradeCreateFixedIndexRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateFixedIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/fixed_index
     * Create fixed chunk index file
     * Create fixed chunk index file.
     * @param backupUpgradeCreateFixedIndexRequest 
     * @return ApiResponse<BackupUpgradeCreateFixedIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateFixedIndexWithHttpInfo(backupUpgradeCreateFixedIndexRequest: BackupUpgradeCreateFixedIndexRequest) : ApiResponse<BackupUpgradeCreateFixedIndexResponse?> {
        val localVariableConfig = backupUpgradeCreateFixedIndexRequestConfig(backupUpgradeCreateFixedIndexRequest = backupUpgradeCreateFixedIndexRequest)

        return request<BackupUpgradeCreateFixedIndexRequest, BackupUpgradeCreateFixedIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateFixedIndex
     *
     * @param backupUpgradeCreateFixedIndexRequest 
     * @return RequestConfig
     */
    fun backupUpgradeCreateFixedIndexRequestConfig(backupUpgradeCreateFixedIndexRequest: BackupUpgradeCreateFixedIndexRequest) : RequestConfig<BackupUpgradeCreateFixedIndexRequest> {
        val localVariableBody = backupUpgradeCreateFixedIndexRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/fixed_index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /backup/_upgrade_/speedtest
     * Test upload speed
     * Test upload speed.
     * @return BackupUpgradeCreateSpeedtestResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeCreateSpeedtest() : BackupUpgradeCreateSpeedtestResponse {
        val localVarResponse = backupUpgradeCreateSpeedtestWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeCreateSpeedtestResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /backup/_upgrade_/speedtest
     * Test upload speed
     * Test upload speed.
     * @return ApiResponse<BackupUpgradeCreateSpeedtestResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeCreateSpeedtestWithHttpInfo() : ApiResponse<BackupUpgradeCreateSpeedtestResponse?> {
        val localVariableConfig = backupUpgradeCreateSpeedtestRequestConfig()

        return request<Unit, BackupUpgradeCreateSpeedtestResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeCreateSpeedtest
     *
     * @return RequestConfig
     */
    fun backupUpgradeCreateSpeedtestRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/backup/_upgrade_/speedtest",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /backup/_upgrade_/previous
     * Download archive from previous backup
     * Download archive from previous backup.
     * @param archiveName Backup archive name.
     * @return BackupUpgradeGetPreviousResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeGetPrevious(archiveName: kotlin.String) : BackupUpgradeGetPreviousResponse {
        val localVarResponse = backupUpgradeGetPreviousWithHttpInfo(archiveName = archiveName)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeGetPreviousResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /backup/_upgrade_/previous
     * Download archive from previous backup
     * Download archive from previous backup.
     * @param archiveName Backup archive name.
     * @return ApiResponse<BackupUpgradeGetPreviousResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeGetPreviousWithHttpInfo(archiveName: kotlin.String) : ApiResponse<BackupUpgradeGetPreviousResponse?> {
        val localVariableConfig = backupUpgradeGetPreviousRequestConfig(archiveName = archiveName)

        return request<Unit, BackupUpgradeGetPreviousResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeGetPrevious
     *
     * @param archiveName Backup archive name.
     * @return RequestConfig
     */
    fun backupUpgradeGetPreviousRequestConfig(archiveName: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("archive-name", listOf(archiveName.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/backup/_upgrade_/previous",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /backup/_upgrade_/previous_backup_time
     * Get previous backup time
     * Get previous backup time.
     * @return BackupUpgradeGetPreviousBackupTimeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeGetPreviousBackupTime() : BackupUpgradeGetPreviousBackupTimeResponse {
        val localVarResponse = backupUpgradeGetPreviousBackupTimeWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeGetPreviousBackupTimeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /backup/_upgrade_/previous_backup_time
     * Get previous backup time
     * Get previous backup time.
     * @return ApiResponse<BackupUpgradeGetPreviousBackupTimeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeGetPreviousBackupTimeWithHttpInfo() : ApiResponse<BackupUpgradeGetPreviousBackupTimeResponse?> {
        val localVariableConfig = backupUpgradeGetPreviousBackupTimeRequestConfig()

        return request<Unit, BackupUpgradeGetPreviousBackupTimeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeGetPreviousBackupTime
     *
     * @return RequestConfig
     */
    fun backupUpgradeGetPreviousBackupTimeRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/backup/_upgrade_/previous_backup_time",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /backup/_upgrade_
     * Directory index
     * Directory index.
     * @return BackupUpgradeGetUpgradeResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeGetUpgrade() : BackupUpgradeGetUpgradeResponse {
        val localVarResponse = backupUpgradeGetUpgradeWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeGetUpgradeResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /backup/_upgrade_
     * Directory index
     * Directory index.
     * @return ApiResponse<BackupUpgradeGetUpgradeResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeGetUpgradeWithHttpInfo() : ApiResponse<BackupUpgradeGetUpgradeResponse?> {
        val localVariableConfig = backupUpgradeGetUpgradeRequestConfig()

        return request<Unit, BackupUpgradeGetUpgradeResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeGetUpgrade
     *
     * @return RequestConfig
     */
    fun backupUpgradeGetUpgradeRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/backup/_upgrade_",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /backup/_upgrade_/dynamic_index
     * Append chunk to dynamic index writer
     * Append chunk to dynamic index writer.
     * @param backupUpgradeUpdateDynamicIndexRequest 
     * @return BackupUpgradeUpdateDynamicIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeUpdateDynamicIndex(backupUpgradeUpdateDynamicIndexRequest: BackupUpgradeUpdateDynamicIndexRequest) : BackupUpgradeUpdateDynamicIndexResponse {
        val localVarResponse = backupUpgradeUpdateDynamicIndexWithHttpInfo(backupUpgradeUpdateDynamicIndexRequest = backupUpgradeUpdateDynamicIndexRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeUpdateDynamicIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /backup/_upgrade_/dynamic_index
     * Append chunk to dynamic index writer
     * Append chunk to dynamic index writer.
     * @param backupUpgradeUpdateDynamicIndexRequest 
     * @return ApiResponse<BackupUpgradeUpdateDynamicIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeUpdateDynamicIndexWithHttpInfo(backupUpgradeUpdateDynamicIndexRequest: BackupUpgradeUpdateDynamicIndexRequest) : ApiResponse<BackupUpgradeUpdateDynamicIndexResponse?> {
        val localVariableConfig = backupUpgradeUpdateDynamicIndexRequestConfig(backupUpgradeUpdateDynamicIndexRequest = backupUpgradeUpdateDynamicIndexRequest)

        return request<BackupUpgradeUpdateDynamicIndexRequest, BackupUpgradeUpdateDynamicIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeUpdateDynamicIndex
     *
     * @param backupUpgradeUpdateDynamicIndexRequest 
     * @return RequestConfig
     */
    fun backupUpgradeUpdateDynamicIndexRequestConfig(backupUpgradeUpdateDynamicIndexRequest: BackupUpgradeUpdateDynamicIndexRequest) : RequestConfig<BackupUpgradeUpdateDynamicIndexRequest> {
        val localVariableBody = backupUpgradeUpdateDynamicIndexRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/backup/_upgrade_/dynamic_index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /backup/_upgrade_/fixed_index
     * Append chunk to fixed index writer
     * Append chunk to fixed index writer.
     * @param backupUpgradeUpdateFixedIndexRequest 
     * @return BackupUpgradeUpdateFixedIndexResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun backupUpgradeUpdateFixedIndex(backupUpgradeUpdateFixedIndexRequest: BackupUpgradeUpdateFixedIndexRequest) : BackupUpgradeUpdateFixedIndexResponse {
        val localVarResponse = backupUpgradeUpdateFixedIndexWithHttpInfo(backupUpgradeUpdateFixedIndexRequest = backupUpgradeUpdateFixedIndexRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BackupUpgradeUpdateFixedIndexResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /backup/_upgrade_/fixed_index
     * Append chunk to fixed index writer
     * Append chunk to fixed index writer.
     * @param backupUpgradeUpdateFixedIndexRequest 
     * @return ApiResponse<BackupUpgradeUpdateFixedIndexResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun backupUpgradeUpdateFixedIndexWithHttpInfo(backupUpgradeUpdateFixedIndexRequest: BackupUpgradeUpdateFixedIndexRequest) : ApiResponse<BackupUpgradeUpdateFixedIndexResponse?> {
        val localVariableConfig = backupUpgradeUpdateFixedIndexRequestConfig(backupUpgradeUpdateFixedIndexRequest = backupUpgradeUpdateFixedIndexRequest)

        return request<BackupUpgradeUpdateFixedIndexRequest, BackupUpgradeUpdateFixedIndexResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation backupUpgradeUpdateFixedIndex
     *
     * @param backupUpgradeUpdateFixedIndexRequest 
     * @return RequestConfig
     */
    fun backupUpgradeUpdateFixedIndexRequestConfig(backupUpgradeUpdateFixedIndexRequest: BackupUpgradeUpdateFixedIndexRequest) : RequestConfig<BackupUpgradeUpdateFixedIndexRequest> {
        val localVariableBody = backupUpgradeUpdateFixedIndexRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/backup/_upgrade_/fixed_index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
