/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigTrafficControlCreateTrafficControlRequest
import com.clientapi.pbs.models.ConfigTrafficControlCreateTrafficControlResponse
import com.clientapi.pbs.models.ConfigTrafficControlDeleteTrafficControlResponse
import com.clientapi.pbs.models.ConfigTrafficControlGetConfigTrafficControlByNameResponse
import com.clientapi.pbs.models.ConfigTrafficControlGetTrafficControlResponse
import com.clientapi.pbs.models.ConfigTrafficControlUpdateTrafficControlRequest
import com.clientapi.pbs.models.ConfigTrafficControlUpdateTrafficControlResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigTrafficControlApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/traffic-control
     * Create new traffic control rule
     * Create new traffic control rule.
     * @param configTrafficControlCreateTrafficControlRequest 
     * @return ConfigTrafficControlCreateTrafficControlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTrafficControlCreateTrafficControl(configTrafficControlCreateTrafficControlRequest: ConfigTrafficControlCreateTrafficControlRequest) : ConfigTrafficControlCreateTrafficControlResponse {
        val localVarResponse = configTrafficControlCreateTrafficControlWithHttpInfo(configTrafficControlCreateTrafficControlRequest = configTrafficControlCreateTrafficControlRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTrafficControlCreateTrafficControlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/traffic-control
     * Create new traffic control rule
     * Create new traffic control rule.
     * @param configTrafficControlCreateTrafficControlRequest 
     * @return ApiResponse<ConfigTrafficControlCreateTrafficControlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTrafficControlCreateTrafficControlWithHttpInfo(configTrafficControlCreateTrafficControlRequest: ConfigTrafficControlCreateTrafficControlRequest) : ApiResponse<ConfigTrafficControlCreateTrafficControlResponse?> {
        val localVariableConfig = configTrafficControlCreateTrafficControlRequestConfig(configTrafficControlCreateTrafficControlRequest = configTrafficControlCreateTrafficControlRequest)

        return request<ConfigTrafficControlCreateTrafficControlRequest, ConfigTrafficControlCreateTrafficControlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTrafficControlCreateTrafficControl
     *
     * @param configTrafficControlCreateTrafficControlRequest 
     * @return RequestConfig
     */
    fun configTrafficControlCreateTrafficControlRequestConfig(configTrafficControlCreateTrafficControlRequest: ConfigTrafficControlCreateTrafficControlRequest) : RequestConfig<ConfigTrafficControlCreateTrafficControlRequest> {
        val localVariableBody = configTrafficControlCreateTrafficControlRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/traffic-control",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/traffic-control/{name}
     * Remove a traffic control rule from the configuration file
     * Remove a traffic control rule from the configuration file.
     * @param name Rule ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigTrafficControlDeleteTrafficControlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTrafficControlDeleteTrafficControl(name: kotlin.String, digest: kotlin.String? = null) : ConfigTrafficControlDeleteTrafficControlResponse {
        val localVarResponse = configTrafficControlDeleteTrafficControlWithHttpInfo(name = name, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTrafficControlDeleteTrafficControlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/traffic-control/{name}
     * Remove a traffic control rule from the configuration file
     * Remove a traffic control rule from the configuration file.
     * @param name Rule ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigTrafficControlDeleteTrafficControlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTrafficControlDeleteTrafficControlWithHttpInfo(name: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigTrafficControlDeleteTrafficControlResponse?> {
        val localVariableConfig = configTrafficControlDeleteTrafficControlRequestConfig(name = name, digest = digest)

        return request<Unit, ConfigTrafficControlDeleteTrafficControlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTrafficControlDeleteTrafficControl
     *
     * @param name Rule ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configTrafficControlDeleteTrafficControlRequestConfig(name: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/traffic-control/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/traffic-control/{name}
     * Read traffic control configuration data
     * Read traffic control configuration data.
     * @param name Rule ID.
     * @return ConfigTrafficControlGetConfigTrafficControlByNameResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTrafficControlGetConfigTrafficControlByName(name: kotlin.String) : ConfigTrafficControlGetConfigTrafficControlByNameResponse {
        val localVarResponse = configTrafficControlGetConfigTrafficControlByNameWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTrafficControlGetConfigTrafficControlByNameResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/traffic-control/{name}
     * Read traffic control configuration data
     * Read traffic control configuration data.
     * @param name Rule ID.
     * @return ApiResponse<ConfigTrafficControlGetConfigTrafficControlByNameResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTrafficControlGetConfigTrafficControlByNameWithHttpInfo(name: kotlin.String) : ApiResponse<ConfigTrafficControlGetConfigTrafficControlByNameResponse?> {
        val localVariableConfig = configTrafficControlGetConfigTrafficControlByNameRequestConfig(name = name)

        return request<Unit, ConfigTrafficControlGetConfigTrafficControlByNameResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTrafficControlGetConfigTrafficControlByName
     *
     * @param name Rule ID.
     * @return RequestConfig
     */
    fun configTrafficControlGetConfigTrafficControlByNameRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/traffic-control/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/traffic-control
     * List traffic control rules
     * List traffic control rules
     * @return ConfigTrafficControlGetTrafficControlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTrafficControlGetTrafficControl() : ConfigTrafficControlGetTrafficControlResponse {
        val localVarResponse = configTrafficControlGetTrafficControlWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTrafficControlGetTrafficControlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/traffic-control
     * List traffic control rules
     * List traffic control rules
     * @return ApiResponse<ConfigTrafficControlGetTrafficControlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTrafficControlGetTrafficControlWithHttpInfo() : ApiResponse<ConfigTrafficControlGetTrafficControlResponse?> {
        val localVariableConfig = configTrafficControlGetTrafficControlRequestConfig()

        return request<Unit, ConfigTrafficControlGetTrafficControlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTrafficControlGetTrafficControl
     *
     * @return RequestConfig
     */
    fun configTrafficControlGetTrafficControlRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/traffic-control",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/traffic-control/{name}
     * Update traffic control configuration
     * Update traffic control configuration.
     * @param name Rule ID.
     * @param configTrafficControlUpdateTrafficControlRequest  (optional)
     * @return ConfigTrafficControlUpdateTrafficControlResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTrafficControlUpdateTrafficControl(name: kotlin.String, configTrafficControlUpdateTrafficControlRequest: ConfigTrafficControlUpdateTrafficControlRequest? = null) : ConfigTrafficControlUpdateTrafficControlResponse {
        val localVarResponse = configTrafficControlUpdateTrafficControlWithHttpInfo(name = name, configTrafficControlUpdateTrafficControlRequest = configTrafficControlUpdateTrafficControlRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTrafficControlUpdateTrafficControlResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/traffic-control/{name}
     * Update traffic control configuration
     * Update traffic control configuration.
     * @param name Rule ID.
     * @param configTrafficControlUpdateTrafficControlRequest  (optional)
     * @return ApiResponse<ConfigTrafficControlUpdateTrafficControlResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTrafficControlUpdateTrafficControlWithHttpInfo(name: kotlin.String, configTrafficControlUpdateTrafficControlRequest: ConfigTrafficControlUpdateTrafficControlRequest?) : ApiResponse<ConfigTrafficControlUpdateTrafficControlResponse?> {
        val localVariableConfig = configTrafficControlUpdateTrafficControlRequestConfig(name = name, configTrafficControlUpdateTrafficControlRequest = configTrafficControlUpdateTrafficControlRequest)

        return request<ConfigTrafficControlUpdateTrafficControlRequest, ConfigTrafficControlUpdateTrafficControlResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTrafficControlUpdateTrafficControl
     *
     * @param name Rule ID.
     * @param configTrafficControlUpdateTrafficControlRequest  (optional)
     * @return RequestConfig
     */
    fun configTrafficControlUpdateTrafficControlRequestConfig(name: kotlin.String, configTrafficControlUpdateTrafficControlRequest: ConfigTrafficControlUpdateTrafficControlRequest?) : RequestConfig<ConfigTrafficControlUpdateTrafficControlRequest> {
        val localVariableBody = configTrafficControlUpdateTrafficControlRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/traffic-control/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
