/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigChangerCreateChangerRequest
import com.clientapi.pbs.models.ConfigChangerCreateChangerResponse
import com.clientapi.pbs.models.ConfigChangerDeleteChangerResponse
import com.clientapi.pbs.models.ConfigChangerGetChangerResponse
import com.clientapi.pbs.models.ConfigChangerGetConfigChangerByNameResponse
import com.clientapi.pbs.models.ConfigChangerUpdateChangerRequest
import com.clientapi.pbs.models.ConfigChangerUpdateChangerResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigChangerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/changer
     * Create a new changer device
     * Create a new changer device
     * @param configChangerCreateChangerRequest 
     * @return ConfigChangerCreateChangerResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configChangerCreateChanger(configChangerCreateChangerRequest: ConfigChangerCreateChangerRequest) : ConfigChangerCreateChangerResponse {
        val localVarResponse = configChangerCreateChangerWithHttpInfo(configChangerCreateChangerRequest = configChangerCreateChangerRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigChangerCreateChangerResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/changer
     * Create a new changer device
     * Create a new changer device
     * @param configChangerCreateChangerRequest 
     * @return ApiResponse<ConfigChangerCreateChangerResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configChangerCreateChangerWithHttpInfo(configChangerCreateChangerRequest: ConfigChangerCreateChangerRequest) : ApiResponse<ConfigChangerCreateChangerResponse?> {
        val localVariableConfig = configChangerCreateChangerRequestConfig(configChangerCreateChangerRequest = configChangerCreateChangerRequest)

        return request<ConfigChangerCreateChangerRequest, ConfigChangerCreateChangerResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configChangerCreateChanger
     *
     * @param configChangerCreateChangerRequest 
     * @return RequestConfig
     */
    fun configChangerCreateChangerRequestConfig(configChangerCreateChangerRequest: ConfigChangerCreateChangerRequest) : RequestConfig<ConfigChangerCreateChangerRequest> {
        val localVariableBody = configChangerCreateChangerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/changer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/changer/{name}
     * Delete a tape changer configuration
     * Delete a tape changer configuration
     * @param name Tape Changer Identifier.
     * @return ConfigChangerDeleteChangerResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configChangerDeleteChanger(name: kotlin.String) : ConfigChangerDeleteChangerResponse {
        val localVarResponse = configChangerDeleteChangerWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigChangerDeleteChangerResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/changer/{name}
     * Delete a tape changer configuration
     * Delete a tape changer configuration
     * @param name Tape Changer Identifier.
     * @return ApiResponse<ConfigChangerDeleteChangerResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configChangerDeleteChangerWithHttpInfo(name: kotlin.String) : ApiResponse<ConfigChangerDeleteChangerResponse?> {
        val localVariableConfig = configChangerDeleteChangerRequestConfig(name = name)

        return request<Unit, ConfigChangerDeleteChangerResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configChangerDeleteChanger
     *
     * @param name Tape Changer Identifier.
     * @return RequestConfig
     */
    fun configChangerDeleteChangerRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/changer/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/changer
     * List changers
     * List changers  Permissions: List configured tape changer filtered by Tape.Audit privileges
     * @return ConfigChangerGetChangerResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configChangerGetChanger() : ConfigChangerGetChangerResponse {
        val localVarResponse = configChangerGetChangerWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigChangerGetChangerResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/changer
     * List changers
     * List changers  Permissions: List configured tape changer filtered by Tape.Audit privileges
     * @return ApiResponse<ConfigChangerGetChangerResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configChangerGetChangerWithHttpInfo() : ApiResponse<ConfigChangerGetChangerResponse?> {
        val localVariableConfig = configChangerGetChangerRequestConfig()

        return request<Unit, ConfigChangerGetChangerResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configChangerGetChanger
     *
     * @return RequestConfig
     */
    fun configChangerGetChangerRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/changer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/changer/{name}
     * Get tape changer configuration
     * Get tape changer configuration
     * @param name Tape Changer Identifier.
     * @return ConfigChangerGetConfigChangerByNameResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configChangerGetConfigChangerByName(name: kotlin.String) : ConfigChangerGetConfigChangerByNameResponse {
        val localVarResponse = configChangerGetConfigChangerByNameWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigChangerGetConfigChangerByNameResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/changer/{name}
     * Get tape changer configuration
     * Get tape changer configuration
     * @param name Tape Changer Identifier.
     * @return ApiResponse<ConfigChangerGetConfigChangerByNameResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configChangerGetConfigChangerByNameWithHttpInfo(name: kotlin.String) : ApiResponse<ConfigChangerGetConfigChangerByNameResponse?> {
        val localVariableConfig = configChangerGetConfigChangerByNameRequestConfig(name = name)

        return request<Unit, ConfigChangerGetConfigChangerByNameResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configChangerGetConfigChangerByName
     *
     * @param name Tape Changer Identifier.
     * @return RequestConfig
     */
    fun configChangerGetConfigChangerByNameRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/changer/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/changer/{name}
     * Update a tape changer configuration
     * Update a tape changer configuration
     * @param name Tape Changer Identifier.
     * @param configChangerUpdateChangerRequest  (optional)
     * @return ConfigChangerUpdateChangerResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configChangerUpdateChanger(name: kotlin.String, configChangerUpdateChangerRequest: ConfigChangerUpdateChangerRequest? = null) : ConfigChangerUpdateChangerResponse {
        val localVarResponse = configChangerUpdateChangerWithHttpInfo(name = name, configChangerUpdateChangerRequest = configChangerUpdateChangerRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigChangerUpdateChangerResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/changer/{name}
     * Update a tape changer configuration
     * Update a tape changer configuration
     * @param name Tape Changer Identifier.
     * @param configChangerUpdateChangerRequest  (optional)
     * @return ApiResponse<ConfigChangerUpdateChangerResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configChangerUpdateChangerWithHttpInfo(name: kotlin.String, configChangerUpdateChangerRequest: ConfigChangerUpdateChangerRequest?) : ApiResponse<ConfigChangerUpdateChangerResponse?> {
        val localVariableConfig = configChangerUpdateChangerRequestConfig(name = name, configChangerUpdateChangerRequest = configChangerUpdateChangerRequest)

        return request<ConfigChangerUpdateChangerRequest, ConfigChangerUpdateChangerResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configChangerUpdateChanger
     *
     * @param name Tape Changer Identifier.
     * @param configChangerUpdateChangerRequest  (optional)
     * @return RequestConfig
     */
    fun configChangerUpdateChangerRequestConfig(name: kotlin.String, configChangerUpdateChangerRequest: ConfigChangerUpdateChangerRequest?) : RequestConfig<ConfigChangerUpdateChangerRequest> {
        val localVariableBody = configChangerUpdateChangerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/changer/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
