/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigAccessCreateAdRequest
import com.clientapi.pbs.models.ConfigAccessCreateAdResponse
import com.clientapi.pbs.models.ConfigAccessCreateLdapRequest
import com.clientapi.pbs.models.ConfigAccessCreateLdapResponse
import com.clientapi.pbs.models.ConfigAccessCreateOpenidRequest
import com.clientapi.pbs.models.ConfigAccessCreateOpenidResponse
import com.clientapi.pbs.models.ConfigAccessDeleteAdResponse
import com.clientapi.pbs.models.ConfigAccessDeleteLdapResponse
import com.clientapi.pbs.models.ConfigAccessDeleteOpenidResponse
import com.clientapi.pbs.models.ConfigAccessGetAccessResponse
import com.clientapi.pbs.models.ConfigAccessGetAdResponse
import com.clientapi.pbs.models.ConfigAccessGetConfigAccessAdByRealmResponse
import com.clientapi.pbs.models.ConfigAccessGetConfigAccessLdapByRealmResponse
import com.clientapi.pbs.models.ConfigAccessGetConfigAccessOpenidByRealmResponse
import com.clientapi.pbs.models.ConfigAccessGetLdapResponse
import com.clientapi.pbs.models.ConfigAccessGetOpenidResponse
import com.clientapi.pbs.models.ConfigAccessGetPamResponse
import com.clientapi.pbs.models.ConfigAccessGetPbsResponse
import com.clientapi.pbs.models.ConfigAccessGetTfaResponse
import com.clientapi.pbs.models.ConfigAccessGetWebauthnResponse
import com.clientapi.pbs.models.ConfigAccessUpdateAdRequest
import com.clientapi.pbs.models.ConfigAccessUpdateAdResponse
import com.clientapi.pbs.models.ConfigAccessUpdateLdapRequest
import com.clientapi.pbs.models.ConfigAccessUpdateLdapResponse
import com.clientapi.pbs.models.ConfigAccessUpdateOpenidRequest
import com.clientapi.pbs.models.ConfigAccessUpdateOpenidResponse
import com.clientapi.pbs.models.ConfigAccessUpdatePamRequest
import com.clientapi.pbs.models.ConfigAccessUpdatePamResponse
import com.clientapi.pbs.models.ConfigAccessUpdatePbsResponse
import com.clientapi.pbs.models.ConfigAccessUpdateWebauthnRequest
import com.clientapi.pbs.models.ConfigAccessUpdateWebauthnResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigAccessApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/access/ad
     * Create a new AD realm
     * Create a new AD realm
     * @param configAccessCreateAdRequest 
     * @return ConfigAccessCreateAdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessCreateAd(configAccessCreateAdRequest: ConfigAccessCreateAdRequest) : ConfigAccessCreateAdResponse {
        val localVarResponse = configAccessCreateAdWithHttpInfo(configAccessCreateAdRequest = configAccessCreateAdRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessCreateAdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/access/ad
     * Create a new AD realm
     * Create a new AD realm
     * @param configAccessCreateAdRequest 
     * @return ApiResponse<ConfigAccessCreateAdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessCreateAdWithHttpInfo(configAccessCreateAdRequest: ConfigAccessCreateAdRequest) : ApiResponse<ConfigAccessCreateAdResponse?> {
        val localVariableConfig = configAccessCreateAdRequestConfig(configAccessCreateAdRequest = configAccessCreateAdRequest)

        return request<ConfigAccessCreateAdRequest, ConfigAccessCreateAdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessCreateAd
     *
     * @param configAccessCreateAdRequest 
     * @return RequestConfig
     */
    fun configAccessCreateAdRequestConfig(configAccessCreateAdRequest: ConfigAccessCreateAdRequest) : RequestConfig<ConfigAccessCreateAdRequest> {
        val localVariableBody = configAccessCreateAdRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/access/ad",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/access/ldap
     * Create a new LDAP realm
     * Create a new LDAP realm
     * @param configAccessCreateLdapRequest 
     * @return ConfigAccessCreateLdapResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessCreateLdap(configAccessCreateLdapRequest: ConfigAccessCreateLdapRequest) : ConfigAccessCreateLdapResponse {
        val localVarResponse = configAccessCreateLdapWithHttpInfo(configAccessCreateLdapRequest = configAccessCreateLdapRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessCreateLdapResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/access/ldap
     * Create a new LDAP realm
     * Create a new LDAP realm
     * @param configAccessCreateLdapRequest 
     * @return ApiResponse<ConfigAccessCreateLdapResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessCreateLdapWithHttpInfo(configAccessCreateLdapRequest: ConfigAccessCreateLdapRequest) : ApiResponse<ConfigAccessCreateLdapResponse?> {
        val localVariableConfig = configAccessCreateLdapRequestConfig(configAccessCreateLdapRequest = configAccessCreateLdapRequest)

        return request<ConfigAccessCreateLdapRequest, ConfigAccessCreateLdapResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessCreateLdap
     *
     * @param configAccessCreateLdapRequest 
     * @return RequestConfig
     */
    fun configAccessCreateLdapRequestConfig(configAccessCreateLdapRequest: ConfigAccessCreateLdapRequest) : RequestConfig<ConfigAccessCreateLdapRequest> {
        val localVariableBody = configAccessCreateLdapRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/access/ldap",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/access/openid
     * Create a new OpenId realm
     * Create a new OpenId realm
     * @param configAccessCreateOpenidRequest 
     * @return ConfigAccessCreateOpenidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessCreateOpenid(configAccessCreateOpenidRequest: ConfigAccessCreateOpenidRequest) : ConfigAccessCreateOpenidResponse {
        val localVarResponse = configAccessCreateOpenidWithHttpInfo(configAccessCreateOpenidRequest = configAccessCreateOpenidRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessCreateOpenidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/access/openid
     * Create a new OpenId realm
     * Create a new OpenId realm
     * @param configAccessCreateOpenidRequest 
     * @return ApiResponse<ConfigAccessCreateOpenidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessCreateOpenidWithHttpInfo(configAccessCreateOpenidRequest: ConfigAccessCreateOpenidRequest) : ApiResponse<ConfigAccessCreateOpenidResponse?> {
        val localVariableConfig = configAccessCreateOpenidRequestConfig(configAccessCreateOpenidRequest = configAccessCreateOpenidRequest)

        return request<ConfigAccessCreateOpenidRequest, ConfigAccessCreateOpenidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessCreateOpenid
     *
     * @param configAccessCreateOpenidRequest 
     * @return RequestConfig
     */
    fun configAccessCreateOpenidRequestConfig(configAccessCreateOpenidRequest: ConfigAccessCreateOpenidRequest) : RequestConfig<ConfigAccessCreateOpenidRequest> {
        val localVariableBody = configAccessCreateOpenidRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/access/openid",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/access/ad/{realm}
     * Remove an LDAP realm configuration
     * Remove an LDAP realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigAccessDeleteAdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessDeleteAd(realm: kotlin.String, digest: kotlin.String? = null) : ConfigAccessDeleteAdResponse {
        val localVarResponse = configAccessDeleteAdWithHttpInfo(realm = realm, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessDeleteAdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/access/ad/{realm}
     * Remove an LDAP realm configuration
     * Remove an LDAP realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigAccessDeleteAdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessDeleteAdWithHttpInfo(realm: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigAccessDeleteAdResponse?> {
        val localVariableConfig = configAccessDeleteAdRequestConfig(realm = realm, digest = digest)

        return request<Unit, ConfigAccessDeleteAdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessDeleteAd
     *
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configAccessDeleteAdRequestConfig(realm: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/access/ad/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/access/ldap/{realm}
     * Remove an LDAP realm configuration
     * Remove an LDAP realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigAccessDeleteLdapResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessDeleteLdap(realm: kotlin.String, digest: kotlin.String? = null) : ConfigAccessDeleteLdapResponse {
        val localVarResponse = configAccessDeleteLdapWithHttpInfo(realm = realm, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessDeleteLdapResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/access/ldap/{realm}
     * Remove an LDAP realm configuration
     * Remove an LDAP realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigAccessDeleteLdapResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessDeleteLdapWithHttpInfo(realm: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigAccessDeleteLdapResponse?> {
        val localVariableConfig = configAccessDeleteLdapRequestConfig(realm = realm, digest = digest)

        return request<Unit, ConfigAccessDeleteLdapResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessDeleteLdap
     *
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configAccessDeleteLdapRequestConfig(realm: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/access/ldap/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/access/openid/{realm}
     * Remove a OpenID realm configuration
     * Remove a OpenID realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigAccessDeleteOpenidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessDeleteOpenid(realm: kotlin.String, digest: kotlin.String? = null) : ConfigAccessDeleteOpenidResponse {
        val localVarResponse = configAccessDeleteOpenidWithHttpInfo(realm = realm, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessDeleteOpenidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/access/openid/{realm}
     * Remove a OpenID realm configuration
     * Remove a OpenID realm configuration
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigAccessDeleteOpenidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessDeleteOpenidWithHttpInfo(realm: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigAccessDeleteOpenidResponse?> {
        val localVariableConfig = configAccessDeleteOpenidRequestConfig(realm = realm, digest = digest)

        return request<Unit, ConfigAccessDeleteOpenidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessDeleteOpenid
     *
     * @param realm Realm name.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configAccessDeleteOpenidRequestConfig(realm: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/access/openid/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access
     * Directory index
     * Directory index.
     * @return ConfigAccessGetAccessResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetAccess() : ConfigAccessGetAccessResponse {
        val localVarResponse = configAccessGetAccessWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetAccessResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access
     * Directory index
     * Directory index.
     * @return ApiResponse<ConfigAccessGetAccessResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetAccessWithHttpInfo() : ApiResponse<ConfigAccessGetAccessResponse?> {
        val localVariableConfig = configAccessGetAccessRequestConfig()

        return request<Unit, ConfigAccessGetAccessResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetAccess
     *
     * @return RequestConfig
     */
    fun configAccessGetAccessRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/ad
     * List configured AD realms
     * List configured AD realms
     * @return ConfigAccessGetAdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetAd() : ConfigAccessGetAdResponse {
        val localVarResponse = configAccessGetAdWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetAdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/ad
     * List configured AD realms
     * List configured AD realms
     * @return ApiResponse<ConfigAccessGetAdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetAdWithHttpInfo() : ApiResponse<ConfigAccessGetAdResponse?> {
        val localVariableConfig = configAccessGetAdRequestConfig()

        return request<Unit, ConfigAccessGetAdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetAd
     *
     * @return RequestConfig
     */
    fun configAccessGetAdRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/ad",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/ad/{realm}
     * Read the AD realm configuration
     * Read the AD realm configuration
     * @param realm Realm name.
     * @return ConfigAccessGetConfigAccessAdByRealmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetConfigAccessAdByRealm(realm: kotlin.String) : ConfigAccessGetConfigAccessAdByRealmResponse {
        val localVarResponse = configAccessGetConfigAccessAdByRealmWithHttpInfo(realm = realm)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetConfigAccessAdByRealmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/ad/{realm}
     * Read the AD realm configuration
     * Read the AD realm configuration
     * @param realm Realm name.
     * @return ApiResponse<ConfigAccessGetConfigAccessAdByRealmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetConfigAccessAdByRealmWithHttpInfo(realm: kotlin.String) : ApiResponse<ConfigAccessGetConfigAccessAdByRealmResponse?> {
        val localVariableConfig = configAccessGetConfigAccessAdByRealmRequestConfig(realm = realm)

        return request<Unit, ConfigAccessGetConfigAccessAdByRealmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetConfigAccessAdByRealm
     *
     * @param realm Realm name.
     * @return RequestConfig
     */
    fun configAccessGetConfigAccessAdByRealmRequestConfig(realm: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/ad/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/ldap/{realm}
     * Read the LDAP realm configuration
     * Read the LDAP realm configuration
     * @param realm Realm name.
     * @return ConfigAccessGetConfigAccessLdapByRealmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetConfigAccessLdapByRealm(realm: kotlin.String) : ConfigAccessGetConfigAccessLdapByRealmResponse {
        val localVarResponse = configAccessGetConfigAccessLdapByRealmWithHttpInfo(realm = realm)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetConfigAccessLdapByRealmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/ldap/{realm}
     * Read the LDAP realm configuration
     * Read the LDAP realm configuration
     * @param realm Realm name.
     * @return ApiResponse<ConfigAccessGetConfigAccessLdapByRealmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetConfigAccessLdapByRealmWithHttpInfo(realm: kotlin.String) : ApiResponse<ConfigAccessGetConfigAccessLdapByRealmResponse?> {
        val localVariableConfig = configAccessGetConfigAccessLdapByRealmRequestConfig(realm = realm)

        return request<Unit, ConfigAccessGetConfigAccessLdapByRealmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetConfigAccessLdapByRealm
     *
     * @param realm Realm name.
     * @return RequestConfig
     */
    fun configAccessGetConfigAccessLdapByRealmRequestConfig(realm: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/ldap/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/openid/{realm}
     * Read the OpenID realm configuration
     * Read the OpenID realm configuration
     * @param realm Realm name.
     * @return ConfigAccessGetConfigAccessOpenidByRealmResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetConfigAccessOpenidByRealm(realm: kotlin.String) : ConfigAccessGetConfigAccessOpenidByRealmResponse {
        val localVarResponse = configAccessGetConfigAccessOpenidByRealmWithHttpInfo(realm = realm)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetConfigAccessOpenidByRealmResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/openid/{realm}
     * Read the OpenID realm configuration
     * Read the OpenID realm configuration
     * @param realm Realm name.
     * @return ApiResponse<ConfigAccessGetConfigAccessOpenidByRealmResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetConfigAccessOpenidByRealmWithHttpInfo(realm: kotlin.String) : ApiResponse<ConfigAccessGetConfigAccessOpenidByRealmResponse?> {
        val localVariableConfig = configAccessGetConfigAccessOpenidByRealmRequestConfig(realm = realm)

        return request<Unit, ConfigAccessGetConfigAccessOpenidByRealmResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetConfigAccessOpenidByRealm
     *
     * @param realm Realm name.
     * @return RequestConfig
     */
    fun configAccessGetConfigAccessOpenidByRealmRequestConfig(realm: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/openid/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/ldap
     * List configured LDAP realms
     * List configured LDAP realms
     * @return ConfigAccessGetLdapResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetLdap() : ConfigAccessGetLdapResponse {
        val localVarResponse = configAccessGetLdapWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetLdapResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/ldap
     * List configured LDAP realms
     * List configured LDAP realms
     * @return ApiResponse<ConfigAccessGetLdapResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetLdapWithHttpInfo() : ApiResponse<ConfigAccessGetLdapResponse?> {
        val localVariableConfig = configAccessGetLdapRequestConfig()

        return request<Unit, ConfigAccessGetLdapResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetLdap
     *
     * @return RequestConfig
     */
    fun configAccessGetLdapRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/ldap",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/openid
     * List configured OpenId realms
     * List configured OpenId realms
     * @return ConfigAccessGetOpenidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetOpenid() : ConfigAccessGetOpenidResponse {
        val localVarResponse = configAccessGetOpenidWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetOpenidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/openid
     * List configured OpenId realms
     * List configured OpenId realms
     * @return ApiResponse<ConfigAccessGetOpenidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetOpenidWithHttpInfo() : ApiResponse<ConfigAccessGetOpenidResponse?> {
        val localVariableConfig = configAccessGetOpenidRequestConfig()

        return request<Unit, ConfigAccessGetOpenidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetOpenid
     *
     * @return RequestConfig
     */
    fun configAccessGetOpenidRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/openid",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/pam
     * Read the PAM realm configuration
     * Read the PAM realm configuration
     * @return ConfigAccessGetPamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetPam() : ConfigAccessGetPamResponse {
        val localVarResponse = configAccessGetPamWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetPamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/pam
     * Read the PAM realm configuration
     * Read the PAM realm configuration
     * @return ApiResponse<ConfigAccessGetPamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetPamWithHttpInfo() : ApiResponse<ConfigAccessGetPamResponse?> {
        val localVariableConfig = configAccessGetPamRequestConfig()

        return request<Unit, ConfigAccessGetPamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetPam
     *
     * @return RequestConfig
     */
    fun configAccessGetPamRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/pam",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/pbs
     * Read the Proxmox Backup authentication server realm configuration
     * Read the Proxmox Backup authentication server realm configuration
     * @return ConfigAccessGetPbsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetPbs() : ConfigAccessGetPbsResponse {
        val localVarResponse = configAccessGetPbsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetPbsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/pbs
     * Read the Proxmox Backup authentication server realm configuration
     * Read the Proxmox Backup authentication server realm configuration
     * @return ApiResponse<ConfigAccessGetPbsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetPbsWithHttpInfo() : ApiResponse<ConfigAccessGetPbsResponse?> {
        val localVariableConfig = configAccessGetPbsRequestConfig()

        return request<Unit, ConfigAccessGetPbsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetPbs
     *
     * @return RequestConfig
     */
    fun configAccessGetPbsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/pbs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/tfa
     * Directory index
     * Directory index.
     * @return ConfigAccessGetTfaResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetTfa() : ConfigAccessGetTfaResponse {
        val localVarResponse = configAccessGetTfaWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetTfaResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/tfa
     * Directory index
     * Directory index.
     * @return ApiResponse<ConfigAccessGetTfaResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetTfaWithHttpInfo() : ApiResponse<ConfigAccessGetTfaResponse?> {
        val localVariableConfig = configAccessGetTfaRequestConfig()

        return request<Unit, ConfigAccessGetTfaResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetTfa
     *
     * @return RequestConfig
     */
    fun configAccessGetTfaRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/tfa",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/access/tfa/webauthn
     * Get the TFA configuration
     * Get the TFA configuration.
     * @return ConfigAccessGetWebauthnResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessGetWebauthn() : ConfigAccessGetWebauthnResponse {
        val localVarResponse = configAccessGetWebauthnWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessGetWebauthnResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/access/tfa/webauthn
     * Get the TFA configuration
     * Get the TFA configuration.
     * @return ApiResponse<ConfigAccessGetWebauthnResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessGetWebauthnWithHttpInfo() : ApiResponse<ConfigAccessGetWebauthnResponse?> {
        val localVariableConfig = configAccessGetWebauthnRequestConfig()

        return request<Unit, ConfigAccessGetWebauthnResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessGetWebauthn
     *
     * @return RequestConfig
     */
    fun configAccessGetWebauthnRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/access/tfa/webauthn",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/ad/{realm}
     * Update an AD realm configuration
     * Update an AD realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateAdRequest  (optional)
     * @return ConfigAccessUpdateAdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdateAd(realm: kotlin.String, configAccessUpdateAdRequest: ConfigAccessUpdateAdRequest? = null) : ConfigAccessUpdateAdResponse {
        val localVarResponse = configAccessUpdateAdWithHttpInfo(realm = realm, configAccessUpdateAdRequest = configAccessUpdateAdRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdateAdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/ad/{realm}
     * Update an AD realm configuration
     * Update an AD realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateAdRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdateAdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdateAdWithHttpInfo(realm: kotlin.String, configAccessUpdateAdRequest: ConfigAccessUpdateAdRequest?) : ApiResponse<ConfigAccessUpdateAdResponse?> {
        val localVariableConfig = configAccessUpdateAdRequestConfig(realm = realm, configAccessUpdateAdRequest = configAccessUpdateAdRequest)

        return request<ConfigAccessUpdateAdRequest, ConfigAccessUpdateAdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdateAd
     *
     * @param realm Realm name.
     * @param configAccessUpdateAdRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdateAdRequestConfig(realm: kotlin.String, configAccessUpdateAdRequest: ConfigAccessUpdateAdRequest?) : RequestConfig<ConfigAccessUpdateAdRequest> {
        val localVariableBody = configAccessUpdateAdRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/ad/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/ldap/{realm}
     * Update an LDAP realm configuration
     * Update an LDAP realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateLdapRequest  (optional)
     * @return ConfigAccessUpdateLdapResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdateLdap(realm: kotlin.String, configAccessUpdateLdapRequest: ConfigAccessUpdateLdapRequest? = null) : ConfigAccessUpdateLdapResponse {
        val localVarResponse = configAccessUpdateLdapWithHttpInfo(realm = realm, configAccessUpdateLdapRequest = configAccessUpdateLdapRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdateLdapResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/ldap/{realm}
     * Update an LDAP realm configuration
     * Update an LDAP realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateLdapRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdateLdapResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdateLdapWithHttpInfo(realm: kotlin.String, configAccessUpdateLdapRequest: ConfigAccessUpdateLdapRequest?) : ApiResponse<ConfigAccessUpdateLdapResponse?> {
        val localVariableConfig = configAccessUpdateLdapRequestConfig(realm = realm, configAccessUpdateLdapRequest = configAccessUpdateLdapRequest)

        return request<ConfigAccessUpdateLdapRequest, ConfigAccessUpdateLdapResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdateLdap
     *
     * @param realm Realm name.
     * @param configAccessUpdateLdapRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdateLdapRequestConfig(realm: kotlin.String, configAccessUpdateLdapRequest: ConfigAccessUpdateLdapRequest?) : RequestConfig<ConfigAccessUpdateLdapRequest> {
        val localVariableBody = configAccessUpdateLdapRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/ldap/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/openid/{realm}
     * Update an OpenID realm configuration
     * Update an OpenID realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateOpenidRequest  (optional)
     * @return ConfigAccessUpdateOpenidResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdateOpenid(realm: kotlin.String, configAccessUpdateOpenidRequest: ConfigAccessUpdateOpenidRequest? = null) : ConfigAccessUpdateOpenidResponse {
        val localVarResponse = configAccessUpdateOpenidWithHttpInfo(realm = realm, configAccessUpdateOpenidRequest = configAccessUpdateOpenidRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdateOpenidResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/openid/{realm}
     * Update an OpenID realm configuration
     * Update an OpenID realm configuration
     * @param realm Realm name.
     * @param configAccessUpdateOpenidRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdateOpenidResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdateOpenidWithHttpInfo(realm: kotlin.String, configAccessUpdateOpenidRequest: ConfigAccessUpdateOpenidRequest?) : ApiResponse<ConfigAccessUpdateOpenidResponse?> {
        val localVariableConfig = configAccessUpdateOpenidRequestConfig(realm = realm, configAccessUpdateOpenidRequest = configAccessUpdateOpenidRequest)

        return request<ConfigAccessUpdateOpenidRequest, ConfigAccessUpdateOpenidResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdateOpenid
     *
     * @param realm Realm name.
     * @param configAccessUpdateOpenidRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdateOpenidRequestConfig(realm: kotlin.String, configAccessUpdateOpenidRequest: ConfigAccessUpdateOpenidRequest?) : RequestConfig<ConfigAccessUpdateOpenidRequest> {
        val localVariableBody = configAccessUpdateOpenidRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/openid/{realm}".replace("{"+"realm"+"}", encodeURIComponent(realm.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/pam
     * Update the PAM realm configuration
     * Update the PAM realm configuration
     * @param configAccessUpdatePamRequest  (optional)
     * @return ConfigAccessUpdatePamResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdatePam(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest? = null) : ConfigAccessUpdatePamResponse {
        val localVarResponse = configAccessUpdatePamWithHttpInfo(configAccessUpdatePamRequest = configAccessUpdatePamRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdatePamResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/pam
     * Update the PAM realm configuration
     * Update the PAM realm configuration
     * @param configAccessUpdatePamRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdatePamResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdatePamWithHttpInfo(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest?) : ApiResponse<ConfigAccessUpdatePamResponse?> {
        val localVariableConfig = configAccessUpdatePamRequestConfig(configAccessUpdatePamRequest = configAccessUpdatePamRequest)

        return request<ConfigAccessUpdatePamRequest, ConfigAccessUpdatePamResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdatePam
     *
     * @param configAccessUpdatePamRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdatePamRequestConfig(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest?) : RequestConfig<ConfigAccessUpdatePamRequest> {
        val localVariableBody = configAccessUpdatePamRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/pam",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/pbs
     * Update the Proxmox Backup authentication server realm configuration
     * Update the Proxmox Backup authentication server realm configuration
     * @param configAccessUpdatePamRequest  (optional)
     * @return ConfigAccessUpdatePbsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdatePbs(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest? = null) : ConfigAccessUpdatePbsResponse {
        val localVarResponse = configAccessUpdatePbsWithHttpInfo(configAccessUpdatePamRequest = configAccessUpdatePamRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdatePbsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/pbs
     * Update the Proxmox Backup authentication server realm configuration
     * Update the Proxmox Backup authentication server realm configuration
     * @param configAccessUpdatePamRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdatePbsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdatePbsWithHttpInfo(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest?) : ApiResponse<ConfigAccessUpdatePbsResponse?> {
        val localVariableConfig = configAccessUpdatePbsRequestConfig(configAccessUpdatePamRequest = configAccessUpdatePamRequest)

        return request<ConfigAccessUpdatePamRequest, ConfigAccessUpdatePbsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdatePbs
     *
     * @param configAccessUpdatePamRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdatePbsRequestConfig(configAccessUpdatePamRequest: ConfigAccessUpdatePamRequest?) : RequestConfig<ConfigAccessUpdatePamRequest> {
        val localVariableBody = configAccessUpdatePamRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/pbs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/access/tfa/webauthn
     * Update the TFA configuration
     * Update the TFA configuration.
     * @param configAccessUpdateWebauthnRequest  (optional)
     * @return ConfigAccessUpdateWebauthnResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configAccessUpdateWebauthn(configAccessUpdateWebauthnRequest: ConfigAccessUpdateWebauthnRequest? = null) : ConfigAccessUpdateWebauthnResponse {
        val localVarResponse = configAccessUpdateWebauthnWithHttpInfo(configAccessUpdateWebauthnRequest = configAccessUpdateWebauthnRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigAccessUpdateWebauthnResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/access/tfa/webauthn
     * Update the TFA configuration
     * Update the TFA configuration.
     * @param configAccessUpdateWebauthnRequest  (optional)
     * @return ApiResponse<ConfigAccessUpdateWebauthnResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configAccessUpdateWebauthnWithHttpInfo(configAccessUpdateWebauthnRequest: ConfigAccessUpdateWebauthnRequest?) : ApiResponse<ConfigAccessUpdateWebauthnResponse?> {
        val localVariableConfig = configAccessUpdateWebauthnRequestConfig(configAccessUpdateWebauthnRequest = configAccessUpdateWebauthnRequest)

        return request<ConfigAccessUpdateWebauthnRequest, ConfigAccessUpdateWebauthnResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configAccessUpdateWebauthn
     *
     * @param configAccessUpdateWebauthnRequest  (optional)
     * @return RequestConfig
     */
    fun configAccessUpdateWebauthnRequestConfig(configAccessUpdateWebauthnRequest: ConfigAccessUpdateWebauthnRequest?) : RequestConfig<ConfigAccessUpdateWebauthnRequest> {
        val localVariableBody = configAccessUpdateWebauthnRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/access/tfa/webauthn",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
