/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigRemoteCreateRemoteRequest
import com.clientapi.pbs.models.ConfigRemoteCreateRemoteResponse
import com.clientapi.pbs.models.ConfigRemoteDeleteRemoteResponse
import com.clientapi.pbs.models.ConfigRemoteGetConfigRemoteByNameResponse
import com.clientapi.pbs.models.ConfigRemoteGetConfigRemoteByNameScanByStoreResponse
import com.clientapi.pbs.models.ConfigRemoteGetGroupsResponse
import com.clientapi.pbs.models.ConfigRemoteGetNamespacesResponse
import com.clientapi.pbs.models.ConfigRemoteGetRemoteResponse
import com.clientapi.pbs.models.ConfigRemoteGetScanResponse
import com.clientapi.pbs.models.ConfigRemoteUpdateRemoteRequest
import com.clientapi.pbs.models.ConfigRemoteUpdateRemoteResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigRemoteApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/remote
     * Create new remote
     * Create new remote.
     * @param configRemoteCreateRemoteRequest 
     * @return ConfigRemoteCreateRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteCreateRemote(configRemoteCreateRemoteRequest: ConfigRemoteCreateRemoteRequest) : ConfigRemoteCreateRemoteResponse {
        val localVarResponse = configRemoteCreateRemoteWithHttpInfo(configRemoteCreateRemoteRequest = configRemoteCreateRemoteRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteCreateRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/remote
     * Create new remote
     * Create new remote.
     * @param configRemoteCreateRemoteRequest 
     * @return ApiResponse<ConfigRemoteCreateRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteCreateRemoteWithHttpInfo(configRemoteCreateRemoteRequest: ConfigRemoteCreateRemoteRequest) : ApiResponse<ConfigRemoteCreateRemoteResponse?> {
        val localVariableConfig = configRemoteCreateRemoteRequestConfig(configRemoteCreateRemoteRequest = configRemoteCreateRemoteRequest)

        return request<ConfigRemoteCreateRemoteRequest, ConfigRemoteCreateRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteCreateRemote
     *
     * @param configRemoteCreateRemoteRequest 
     * @return RequestConfig
     */
    fun configRemoteCreateRemoteRequestConfig(configRemoteCreateRemoteRequest: ConfigRemoteCreateRemoteRequest) : RequestConfig<ConfigRemoteCreateRemoteRequest> {
        val localVariableBody = configRemoteCreateRemoteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/remote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/remote/{name}
     * Remove a remote from the configuration file
     * Remove a remote from the configuration file.
     * @param name Remote ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigRemoteDeleteRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteDeleteRemote(name: kotlin.String, digest: kotlin.String? = null) : ConfigRemoteDeleteRemoteResponse {
        val localVarResponse = configRemoteDeleteRemoteWithHttpInfo(name = name, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteDeleteRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/remote/{name}
     * Remove a remote from the configuration file
     * Remove a remote from the configuration file.
     * @param name Remote ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigRemoteDeleteRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteDeleteRemoteWithHttpInfo(name: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigRemoteDeleteRemoteResponse?> {
        val localVariableConfig = configRemoteDeleteRemoteRequestConfig(name = name, digest = digest)

        return request<Unit, ConfigRemoteDeleteRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteDeleteRemote
     *
     * @param name Remote ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configRemoteDeleteRemoteRequestConfig(name: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/remote/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote/{name}
     * Read remote configuration data
     * Read remote configuration data.
     * @param name Remote ID.
     * @return ConfigRemoteGetConfigRemoteByNameResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetConfigRemoteByName(name: kotlin.String) : ConfigRemoteGetConfigRemoteByNameResponse {
        val localVarResponse = configRemoteGetConfigRemoteByNameWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetConfigRemoteByNameResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote/{name}
     * Read remote configuration data
     * Read remote configuration data.
     * @param name Remote ID.
     * @return ApiResponse<ConfigRemoteGetConfigRemoteByNameResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetConfigRemoteByNameWithHttpInfo(name: kotlin.String) : ApiResponse<ConfigRemoteGetConfigRemoteByNameResponse?> {
        val localVariableConfig = configRemoteGetConfigRemoteByNameRequestConfig(name = name)

        return request<Unit, ConfigRemoteGetConfigRemoteByNameResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetConfigRemoteByName
     *
     * @param name Remote ID.
     * @return RequestConfig
     */
    fun configRemoteGetConfigRemoteByNameRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote/{name}/scan/{store}
     * Directory index
     * Directory index.
     * @param name 
     * @param store 
     * @return ConfigRemoteGetConfigRemoteByNameScanByStoreResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetConfigRemoteByNameScanByStore(name: kotlin.String, store: kotlin.String) : ConfigRemoteGetConfigRemoteByNameScanByStoreResponse {
        val localVarResponse = configRemoteGetConfigRemoteByNameScanByStoreWithHttpInfo(name = name, store = store)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetConfigRemoteByNameScanByStoreResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote/{name}/scan/{store}
     * Directory index
     * Directory index.
     * @param name 
     * @param store 
     * @return ApiResponse<ConfigRemoteGetConfigRemoteByNameScanByStoreResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetConfigRemoteByNameScanByStoreWithHttpInfo(name: kotlin.String, store: kotlin.String) : ApiResponse<ConfigRemoteGetConfigRemoteByNameScanByStoreResponse?> {
        val localVariableConfig = configRemoteGetConfigRemoteByNameScanByStoreRequestConfig(name = name, store = store)

        return request<Unit, ConfigRemoteGetConfigRemoteByNameScanByStoreResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetConfigRemoteByNameScanByStore
     *
     * @param name 
     * @param store 
     * @return RequestConfig
     */
    fun configRemoteGetConfigRemoteByNameScanByStoreRequestConfig(name: kotlin.String, store: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote/{name}/scan/{store}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"store"+"}", encodeURIComponent(store.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote/{name}/scan/{store}/groups
     * List groups of a remote
     * List groups of a remote.cfg entry&#39;s datastore
     * @param name Remote ID.
     * @param store Datastore name.
     * @param namespace Namespace. (optional)
     * @return ConfigRemoteGetGroupsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetGroups(name: kotlin.String, store: kotlin.String, namespace: kotlin.String? = null) : ConfigRemoteGetGroupsResponse {
        val localVarResponse = configRemoteGetGroupsWithHttpInfo(name = name, store = store, namespace = namespace)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetGroupsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote/{name}/scan/{store}/groups
     * List groups of a remote
     * List groups of a remote.cfg entry&#39;s datastore
     * @param name Remote ID.
     * @param store Datastore name.
     * @param namespace Namespace. (optional)
     * @return ApiResponse<ConfigRemoteGetGroupsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetGroupsWithHttpInfo(name: kotlin.String, store: kotlin.String, namespace: kotlin.String?) : ApiResponse<ConfigRemoteGetGroupsResponse?> {
        val localVariableConfig = configRemoteGetGroupsRequestConfig(name = name, store = store, namespace = namespace)

        return request<Unit, ConfigRemoteGetGroupsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetGroups
     *
     * @param name Remote ID.
     * @param store Datastore name.
     * @param namespace Namespace. (optional)
     * @return RequestConfig
     */
    fun configRemoteGetGroupsRequestConfig(name: kotlin.String, store: kotlin.String, namespace: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (namespace != null) {
                    put("namespace", listOf(namespace.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote/{name}/scan/{store}/groups".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"store"+"}", encodeURIComponent(store.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote/{name}/scan/{store}/namespaces
     * List namespaces of a datastore of a remote
     * List namespaces of a datastore of a remote.cfg entry
     * @param name Remote ID.
     * @param store Datastore name.
     * @return ConfigRemoteGetNamespacesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetNamespaces(name: kotlin.String, store: kotlin.String) : ConfigRemoteGetNamespacesResponse {
        val localVarResponse = configRemoteGetNamespacesWithHttpInfo(name = name, store = store)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetNamespacesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote/{name}/scan/{store}/namespaces
     * List namespaces of a datastore of a remote
     * List namespaces of a datastore of a remote.cfg entry
     * @param name Remote ID.
     * @param store Datastore name.
     * @return ApiResponse<ConfigRemoteGetNamespacesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetNamespacesWithHttpInfo(name: kotlin.String, store: kotlin.String) : ApiResponse<ConfigRemoteGetNamespacesResponse?> {
        val localVariableConfig = configRemoteGetNamespacesRequestConfig(name = name, store = store)

        return request<Unit, ConfigRemoteGetNamespacesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetNamespaces
     *
     * @param name Remote ID.
     * @param store Datastore name.
     * @return RequestConfig
     */
    fun configRemoteGetNamespacesRequestConfig(name: kotlin.String, store: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote/{name}/scan/{store}/namespaces".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"store"+"}", encodeURIComponent(store.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote
     * List all remotes
     * List all remotes  Permissions: List configured remotes filtered by Remote.Audit privileges
     * @return ConfigRemoteGetRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetRemote() : ConfigRemoteGetRemoteResponse {
        val localVarResponse = configRemoteGetRemoteWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote
     * List all remotes
     * List all remotes  Permissions: List configured remotes filtered by Remote.Audit privileges
     * @return ApiResponse<ConfigRemoteGetRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetRemoteWithHttpInfo() : ApiResponse<ConfigRemoteGetRemoteResponse?> {
        val localVariableConfig = configRemoteGetRemoteRequestConfig()

        return request<Unit, ConfigRemoteGetRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetRemote
     *
     * @return RequestConfig
     */
    fun configRemoteGetRemoteRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/remote/{name}/scan
     * List datastores of a remote
     * List datastores of a remote.cfg entry
     * @param name Remote ID.
     * @return ConfigRemoteGetScanResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteGetScan(name: kotlin.String) : ConfigRemoteGetScanResponse {
        val localVarResponse = configRemoteGetScanWithHttpInfo(name = name)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteGetScanResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/remote/{name}/scan
     * List datastores of a remote
     * List datastores of a remote.cfg entry
     * @param name Remote ID.
     * @return ApiResponse<ConfigRemoteGetScanResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteGetScanWithHttpInfo(name: kotlin.String) : ApiResponse<ConfigRemoteGetScanResponse?> {
        val localVariableConfig = configRemoteGetScanRequestConfig(name = name)

        return request<Unit, ConfigRemoteGetScanResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteGetScan
     *
     * @param name Remote ID.
     * @return RequestConfig
     */
    fun configRemoteGetScanRequestConfig(name: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/remote/{name}/scan".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/remote/{name}
     * Update remote configuration
     * Update remote configuration.
     * @param name Remote ID.
     * @param configRemoteUpdateRemoteRequest  (optional)
     * @return ConfigRemoteUpdateRemoteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configRemoteUpdateRemote(name: kotlin.String, configRemoteUpdateRemoteRequest: ConfigRemoteUpdateRemoteRequest? = null) : ConfigRemoteUpdateRemoteResponse {
        val localVarResponse = configRemoteUpdateRemoteWithHttpInfo(name = name, configRemoteUpdateRemoteRequest = configRemoteUpdateRemoteRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigRemoteUpdateRemoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/remote/{name}
     * Update remote configuration
     * Update remote configuration.
     * @param name Remote ID.
     * @param configRemoteUpdateRemoteRequest  (optional)
     * @return ApiResponse<ConfigRemoteUpdateRemoteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configRemoteUpdateRemoteWithHttpInfo(name: kotlin.String, configRemoteUpdateRemoteRequest: ConfigRemoteUpdateRemoteRequest?) : ApiResponse<ConfigRemoteUpdateRemoteResponse?> {
        val localVariableConfig = configRemoteUpdateRemoteRequestConfig(name = name, configRemoteUpdateRemoteRequest = configRemoteUpdateRemoteRequest)

        return request<ConfigRemoteUpdateRemoteRequest, ConfigRemoteUpdateRemoteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configRemoteUpdateRemote
     *
     * @param name Remote ID.
     * @param configRemoteUpdateRemoteRequest  (optional)
     * @return RequestConfig
     */
    fun configRemoteUpdateRemoteRequestConfig(name: kotlin.String, configRemoteUpdateRemoteRequest: ConfigRemoteUpdateRemoteRequest?) : RequestConfig<ConfigRemoteUpdateRemoteRequest> {
        val localVariableBody = configRemoteUpdateRemoteRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/remote/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
