/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigPruneCreatePruneRequest
import com.clientapi.pbs.models.ConfigPruneCreatePruneResponse
import com.clientapi.pbs.models.ConfigPruneDeletePruneResponse
import com.clientapi.pbs.models.ConfigPruneGetConfigPruneByIdResponse
import com.clientapi.pbs.models.ConfigPruneGetPruneResponse
import com.clientapi.pbs.models.ConfigPruneUpdatePruneRequest
import com.clientapi.pbs.models.ConfigPruneUpdatePruneResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigPruneApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/prune
     * Create a new prune job
     * Create a new prune job.  Permissions: Requires Datastore.Modify on job&#39;s datastore.
     * @param configPruneCreatePruneRequest 
     * @return ConfigPruneCreatePruneResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configPruneCreatePrune(configPruneCreatePruneRequest: ConfigPruneCreatePruneRequest) : ConfigPruneCreatePruneResponse {
        val localVarResponse = configPruneCreatePruneWithHttpInfo(configPruneCreatePruneRequest = configPruneCreatePruneRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigPruneCreatePruneResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/prune
     * Create a new prune job
     * Create a new prune job.  Permissions: Requires Datastore.Modify on job&#39;s datastore.
     * @param configPruneCreatePruneRequest 
     * @return ApiResponse<ConfigPruneCreatePruneResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configPruneCreatePruneWithHttpInfo(configPruneCreatePruneRequest: ConfigPruneCreatePruneRequest) : ApiResponse<ConfigPruneCreatePruneResponse?> {
        val localVariableConfig = configPruneCreatePruneRequestConfig(configPruneCreatePruneRequest = configPruneCreatePruneRequest)

        return request<ConfigPruneCreatePruneRequest, ConfigPruneCreatePruneResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configPruneCreatePrune
     *
     * @param configPruneCreatePruneRequest 
     * @return RequestConfig
     */
    fun configPruneCreatePruneRequestConfig(configPruneCreatePruneRequest: ConfigPruneCreatePruneRequest) : RequestConfig<ConfigPruneCreatePruneRequest> {
        val localVariableBody = configPruneCreatePruneRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/prune",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/prune/{id}
     * Remove a prune job configuration
     * Remove a prune job configuration  Permissions: Requires Datastore.Verify on job&#39;s datastore.
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigPruneDeletePruneResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configPruneDeletePrune(id: kotlin.String, digest: kotlin.String? = null) : ConfigPruneDeletePruneResponse {
        val localVarResponse = configPruneDeletePruneWithHttpInfo(id = id, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigPruneDeletePruneResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/prune/{id}
     * Remove a prune job configuration
     * Remove a prune job configuration  Permissions: Requires Datastore.Verify on job&#39;s datastore.
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigPruneDeletePruneResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configPruneDeletePruneWithHttpInfo(id: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigPruneDeletePruneResponse?> {
        val localVariableConfig = configPruneDeletePruneRequestConfig(id = id, digest = digest)

        return request<Unit, ConfigPruneDeletePruneResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configPruneDeletePrune
     *
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configPruneDeletePruneRequestConfig(id: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/prune/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/prune/{id}
     * Read a prune job configuration
     * Read a prune job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job&#39;s datastore.
     * @param id Job ID.
     * @return ConfigPruneGetConfigPruneByIdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configPruneGetConfigPruneById(id: kotlin.String) : ConfigPruneGetConfigPruneByIdResponse {
        val localVarResponse = configPruneGetConfigPruneByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigPruneGetConfigPruneByIdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/prune/{id}
     * Read a prune job configuration
     * Read a prune job configuration.  Permissions: Requires Datastore.Audit or Datastore.Verify on job&#39;s datastore.
     * @param id Job ID.
     * @return ApiResponse<ConfigPruneGetConfigPruneByIdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configPruneGetConfigPruneByIdWithHttpInfo(id: kotlin.String) : ApiResponse<ConfigPruneGetConfigPruneByIdResponse?> {
        val localVariableConfig = configPruneGetConfigPruneByIdRequestConfig(id = id)

        return request<Unit, ConfigPruneGetConfigPruneByIdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configPruneGetConfigPruneById
     *
     * @param id Job ID.
     * @return RequestConfig
     */
    fun configPruneGetConfigPruneByIdRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/prune/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/prune
     * List all scheduled prune jobs
     * List all scheduled prune jobs.  Permissions: Requires Datastore.Audit.
     * @return ConfigPruneGetPruneResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configPruneGetPrune() : ConfigPruneGetPruneResponse {
        val localVarResponse = configPruneGetPruneWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigPruneGetPruneResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/prune
     * List all scheduled prune jobs
     * List all scheduled prune jobs.  Permissions: Requires Datastore.Audit.
     * @return ApiResponse<ConfigPruneGetPruneResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configPruneGetPruneWithHttpInfo() : ApiResponse<ConfigPruneGetPruneResponse?> {
        val localVariableConfig = configPruneGetPruneRequestConfig()

        return request<Unit, ConfigPruneGetPruneResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configPruneGetPrune
     *
     * @return RequestConfig
     */
    fun configPruneGetPruneRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/prune",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/prune/{id}
     * Update prune job config
     * Update prune job config.  Permissions: Requires Datastore.Modify on job&#39;s datastore.
     * @param id Job ID.
     * @param configPruneUpdatePruneRequest  (optional)
     * @return ConfigPruneUpdatePruneResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configPruneUpdatePrune(id: kotlin.String, configPruneUpdatePruneRequest: ConfigPruneUpdatePruneRequest? = null) : ConfigPruneUpdatePruneResponse {
        val localVarResponse = configPruneUpdatePruneWithHttpInfo(id = id, configPruneUpdatePruneRequest = configPruneUpdatePruneRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigPruneUpdatePruneResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/prune/{id}
     * Update prune job config
     * Update prune job config.  Permissions: Requires Datastore.Modify on job&#39;s datastore.
     * @param id Job ID.
     * @param configPruneUpdatePruneRequest  (optional)
     * @return ApiResponse<ConfigPruneUpdatePruneResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configPruneUpdatePruneWithHttpInfo(id: kotlin.String, configPruneUpdatePruneRequest: ConfigPruneUpdatePruneRequest?) : ApiResponse<ConfigPruneUpdatePruneResponse?> {
        val localVariableConfig = configPruneUpdatePruneRequestConfig(id = id, configPruneUpdatePruneRequest = configPruneUpdatePruneRequest)

        return request<ConfigPruneUpdatePruneRequest, ConfigPruneUpdatePruneResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configPruneUpdatePrune
     *
     * @param id Job ID.
     * @param configPruneUpdatePruneRequest  (optional)
     * @return RequestConfig
     */
    fun configPruneUpdatePruneRequestConfig(id: kotlin.String, configPruneUpdatePruneRequest: ConfigPruneUpdatePruneRequest?) : RequestConfig<ConfigPruneUpdatePruneRequest> {
        val localVariableBody = configPruneUpdatePruneRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/prune/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
