/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigTapeBackupJobCreateTapeBackupJobRequest
import com.clientapi.pbs.models.ConfigTapeBackupJobCreateTapeBackupJobResponse
import com.clientapi.pbs.models.ConfigTapeBackupJobDeleteTapeBackupJobResponse
import com.clientapi.pbs.models.ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse
import com.clientapi.pbs.models.ConfigTapeBackupJobGetTapeBackupJobResponse
import com.clientapi.pbs.models.ConfigTapeBackupJobUpdateTapeBackupJobRequest
import com.clientapi.pbs.models.ConfigTapeBackupJobUpdateTapeBackupJobResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigTapeBackupJobApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/tape-backup-job
     * Create a new tape backup job
     * Create a new tape backup job.
     * @param configTapeBackupJobCreateTapeBackupJobRequest 
     * @return ConfigTapeBackupJobCreateTapeBackupJobResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTapeBackupJobCreateTapeBackupJob(configTapeBackupJobCreateTapeBackupJobRequest: ConfigTapeBackupJobCreateTapeBackupJobRequest) : ConfigTapeBackupJobCreateTapeBackupJobResponse {
        val localVarResponse = configTapeBackupJobCreateTapeBackupJobWithHttpInfo(configTapeBackupJobCreateTapeBackupJobRequest = configTapeBackupJobCreateTapeBackupJobRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTapeBackupJobCreateTapeBackupJobResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/tape-backup-job
     * Create a new tape backup job
     * Create a new tape backup job.
     * @param configTapeBackupJobCreateTapeBackupJobRequest 
     * @return ApiResponse<ConfigTapeBackupJobCreateTapeBackupJobResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTapeBackupJobCreateTapeBackupJobWithHttpInfo(configTapeBackupJobCreateTapeBackupJobRequest: ConfigTapeBackupJobCreateTapeBackupJobRequest) : ApiResponse<ConfigTapeBackupJobCreateTapeBackupJobResponse?> {
        val localVariableConfig = configTapeBackupJobCreateTapeBackupJobRequestConfig(configTapeBackupJobCreateTapeBackupJobRequest = configTapeBackupJobCreateTapeBackupJobRequest)

        return request<ConfigTapeBackupJobCreateTapeBackupJobRequest, ConfigTapeBackupJobCreateTapeBackupJobResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTapeBackupJobCreateTapeBackupJob
     *
     * @param configTapeBackupJobCreateTapeBackupJobRequest 
     * @return RequestConfig
     */
    fun configTapeBackupJobCreateTapeBackupJobRequestConfig(configTapeBackupJobCreateTapeBackupJobRequest: ConfigTapeBackupJobCreateTapeBackupJobRequest) : RequestConfig<ConfigTapeBackupJobCreateTapeBackupJobRequest> {
        val localVariableBody = configTapeBackupJobCreateTapeBackupJobRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/tape-backup-job",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/tape-backup-job/{id}
     * Remove a tape backup job configuration
     * Remove a tape backup job configuration
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigTapeBackupJobDeleteTapeBackupJobResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTapeBackupJobDeleteTapeBackupJob(id: kotlin.String, digest: kotlin.String? = null) : ConfigTapeBackupJobDeleteTapeBackupJobResponse {
        val localVarResponse = configTapeBackupJobDeleteTapeBackupJobWithHttpInfo(id = id, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTapeBackupJobDeleteTapeBackupJobResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/tape-backup-job/{id}
     * Remove a tape backup job configuration
     * Remove a tape backup job configuration
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigTapeBackupJobDeleteTapeBackupJobResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTapeBackupJobDeleteTapeBackupJobWithHttpInfo(id: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigTapeBackupJobDeleteTapeBackupJobResponse?> {
        val localVariableConfig = configTapeBackupJobDeleteTapeBackupJobRequestConfig(id = id, digest = digest)

        return request<Unit, ConfigTapeBackupJobDeleteTapeBackupJobResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTapeBackupJobDeleteTapeBackupJob
     *
     * @param id Job ID.
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configTapeBackupJobDeleteTapeBackupJobRequestConfig(id: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/tape-backup-job/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/tape-backup-job/{id}
     * Read a tape backup job configuration
     * Read a tape backup job configuration.
     * @param id Job ID.
     * @return ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTapeBackupJobGetConfigTapeBackupJobById(id: kotlin.String) : ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse {
        val localVarResponse = configTapeBackupJobGetConfigTapeBackupJobByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/tape-backup-job/{id}
     * Read a tape backup job configuration
     * Read a tape backup job configuration.
     * @param id Job ID.
     * @return ApiResponse<ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTapeBackupJobGetConfigTapeBackupJobByIdWithHttpInfo(id: kotlin.String) : ApiResponse<ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse?> {
        val localVariableConfig = configTapeBackupJobGetConfigTapeBackupJobByIdRequestConfig(id = id)

        return request<Unit, ConfigTapeBackupJobGetConfigTapeBackupJobByIdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTapeBackupJobGetConfigTapeBackupJobById
     *
     * @param id Job ID.
     * @return RequestConfig
     */
    fun configTapeBackupJobGetConfigTapeBackupJobByIdRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/tape-backup-job/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/tape-backup-job
     * List all tape backup jobs
     * List all tape backup jobs  Permissions: List configured tape jobs filtered by Tape.Audit privileges
     * @return ConfigTapeBackupJobGetTapeBackupJobResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTapeBackupJobGetTapeBackupJob() : ConfigTapeBackupJobGetTapeBackupJobResponse {
        val localVarResponse = configTapeBackupJobGetTapeBackupJobWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTapeBackupJobGetTapeBackupJobResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/tape-backup-job
     * List all tape backup jobs
     * List all tape backup jobs  Permissions: List configured tape jobs filtered by Tape.Audit privileges
     * @return ApiResponse<ConfigTapeBackupJobGetTapeBackupJobResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTapeBackupJobGetTapeBackupJobWithHttpInfo() : ApiResponse<ConfigTapeBackupJobGetTapeBackupJobResponse?> {
        val localVariableConfig = configTapeBackupJobGetTapeBackupJobRequestConfig()

        return request<Unit, ConfigTapeBackupJobGetTapeBackupJobResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTapeBackupJobGetTapeBackupJob
     *
     * @return RequestConfig
     */
    fun configTapeBackupJobGetTapeBackupJobRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/tape-backup-job",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /config/tape-backup-job/{id}
     * Update the tape backup job
     * Update the tape backup job
     * @param id Job ID.
     * @param configTapeBackupJobUpdateTapeBackupJobRequest  (optional)
     * @return ConfigTapeBackupJobUpdateTapeBackupJobResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configTapeBackupJobUpdateTapeBackupJob(id: kotlin.String, configTapeBackupJobUpdateTapeBackupJobRequest: ConfigTapeBackupJobUpdateTapeBackupJobRequest? = null) : ConfigTapeBackupJobUpdateTapeBackupJobResponse {
        val localVarResponse = configTapeBackupJobUpdateTapeBackupJobWithHttpInfo(id = id, configTapeBackupJobUpdateTapeBackupJobRequest = configTapeBackupJobUpdateTapeBackupJobRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigTapeBackupJobUpdateTapeBackupJobResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /config/tape-backup-job/{id}
     * Update the tape backup job
     * Update the tape backup job
     * @param id Job ID.
     * @param configTapeBackupJobUpdateTapeBackupJobRequest  (optional)
     * @return ApiResponse<ConfigTapeBackupJobUpdateTapeBackupJobResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configTapeBackupJobUpdateTapeBackupJobWithHttpInfo(id: kotlin.String, configTapeBackupJobUpdateTapeBackupJobRequest: ConfigTapeBackupJobUpdateTapeBackupJobRequest?) : ApiResponse<ConfigTapeBackupJobUpdateTapeBackupJobResponse?> {
        val localVariableConfig = configTapeBackupJobUpdateTapeBackupJobRequestConfig(id = id, configTapeBackupJobUpdateTapeBackupJobRequest = configTapeBackupJobUpdateTapeBackupJobRequest)

        return request<ConfigTapeBackupJobUpdateTapeBackupJobRequest, ConfigTapeBackupJobUpdateTapeBackupJobResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configTapeBackupJobUpdateTapeBackupJob
     *
     * @param id Job ID.
     * @param configTapeBackupJobUpdateTapeBackupJobRequest  (optional)
     * @return RequestConfig
     */
    fun configTapeBackupJobUpdateTapeBackupJobRequestConfig(id: kotlin.String, configTapeBackupJobUpdateTapeBackupJobRequest: ConfigTapeBackupJobUpdateTapeBackupJobRequest?) : RequestConfig<ConfigTapeBackupJobUpdateTapeBackupJobRequest> {
        val localVariableBody = configTapeBackupJobUpdateTapeBackupJobRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/config/tape-backup-job/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
