/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest
import com.clientapi.pbs.models.ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse
import com.clientapi.pbs.models.ConfigEncryptionKeysCreateEncryptionKeysRequest
import com.clientapi.pbs.models.ConfigEncryptionKeysCreateEncryptionKeysResponse
import com.clientapi.pbs.models.ConfigEncryptionKeysDeleteEncryptionKeysResponse
import com.clientapi.pbs.models.ConfigEncryptionKeysGetEncryptionKeysResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class ConfigEncryptionKeysApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /config/encryption-keys/{id}
     * Toggle the archive state for the key by given id, archived keys are no longer usable to encrypt contents
     * Toggle the archive state for the key by given id, archived keys are no longer usable to encrypt contents.
     * @param id ID to uniquely identify encryption/decription key
     * @param configEncryptionKeysCreateConfigEncryptionKeysByIdRequest  (optional)
     * @return ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configEncryptionKeysCreateConfigEncryptionKeysById(id: kotlin.String, configEncryptionKeysCreateConfigEncryptionKeysByIdRequest: ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest? = null) : ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse {
        val localVarResponse = configEncryptionKeysCreateConfigEncryptionKeysByIdWithHttpInfo(id = id, configEncryptionKeysCreateConfigEncryptionKeysByIdRequest = configEncryptionKeysCreateConfigEncryptionKeysByIdRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/encryption-keys/{id}
     * Toggle the archive state for the key by given id, archived keys are no longer usable to encrypt contents
     * Toggle the archive state for the key by given id, archived keys are no longer usable to encrypt contents.
     * @param id ID to uniquely identify encryption/decription key
     * @param configEncryptionKeysCreateConfigEncryptionKeysByIdRequest  (optional)
     * @return ApiResponse<ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configEncryptionKeysCreateConfigEncryptionKeysByIdWithHttpInfo(id: kotlin.String, configEncryptionKeysCreateConfigEncryptionKeysByIdRequest: ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest?) : ApiResponse<ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse?> {
        val localVariableConfig = configEncryptionKeysCreateConfigEncryptionKeysByIdRequestConfig(id = id, configEncryptionKeysCreateConfigEncryptionKeysByIdRequest = configEncryptionKeysCreateConfigEncryptionKeysByIdRequest)

        return request<ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest, ConfigEncryptionKeysCreateConfigEncryptionKeysByIdResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configEncryptionKeysCreateConfigEncryptionKeysById
     *
     * @param id ID to uniquely identify encryption/decription key
     * @param configEncryptionKeysCreateConfigEncryptionKeysByIdRequest  (optional)
     * @return RequestConfig
     */
    fun configEncryptionKeysCreateConfigEncryptionKeysByIdRequestConfig(id: kotlin.String, configEncryptionKeysCreateConfigEncryptionKeysByIdRequest: ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest?) : RequestConfig<ConfigEncryptionKeysCreateConfigEncryptionKeysByIdRequest> {
        val localVariableBody = configEncryptionKeysCreateConfigEncryptionKeysByIdRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/encryption-keys/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /config/encryption-keys
     * Create new encryption key instance or use the provided one
     * Create new encryption key instance or use the provided one.
     * @param configEncryptionKeysCreateEncryptionKeysRequest 
     * @return ConfigEncryptionKeysCreateEncryptionKeysResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configEncryptionKeysCreateEncryptionKeys(configEncryptionKeysCreateEncryptionKeysRequest: ConfigEncryptionKeysCreateEncryptionKeysRequest) : ConfigEncryptionKeysCreateEncryptionKeysResponse {
        val localVarResponse = configEncryptionKeysCreateEncryptionKeysWithHttpInfo(configEncryptionKeysCreateEncryptionKeysRequest = configEncryptionKeysCreateEncryptionKeysRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigEncryptionKeysCreateEncryptionKeysResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /config/encryption-keys
     * Create new encryption key instance or use the provided one
     * Create new encryption key instance or use the provided one.
     * @param configEncryptionKeysCreateEncryptionKeysRequest 
     * @return ApiResponse<ConfigEncryptionKeysCreateEncryptionKeysResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configEncryptionKeysCreateEncryptionKeysWithHttpInfo(configEncryptionKeysCreateEncryptionKeysRequest: ConfigEncryptionKeysCreateEncryptionKeysRequest) : ApiResponse<ConfigEncryptionKeysCreateEncryptionKeysResponse?> {
        val localVariableConfig = configEncryptionKeysCreateEncryptionKeysRequestConfig(configEncryptionKeysCreateEncryptionKeysRequest = configEncryptionKeysCreateEncryptionKeysRequest)

        return request<ConfigEncryptionKeysCreateEncryptionKeysRequest, ConfigEncryptionKeysCreateEncryptionKeysResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configEncryptionKeysCreateEncryptionKeys
     *
     * @param configEncryptionKeysCreateEncryptionKeysRequest 
     * @return RequestConfig
     */
    fun configEncryptionKeysCreateEncryptionKeysRequestConfig(configEncryptionKeysCreateEncryptionKeysRequest: ConfigEncryptionKeysCreateEncryptionKeysRequest) : RequestConfig<ConfigEncryptionKeysCreateEncryptionKeysRequest> {
        val localVariableBody = configEncryptionKeysCreateEncryptionKeysRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/config/encryption-keys",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /config/encryption-keys/{id}
     * Remove encryption key
     * Remove encryption key.
     * @param id ID to uniquely identify encryption/decription key
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ConfigEncryptionKeysDeleteEncryptionKeysResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configEncryptionKeysDeleteEncryptionKeys(id: kotlin.String, digest: kotlin.String? = null) : ConfigEncryptionKeysDeleteEncryptionKeysResponse {
        val localVarResponse = configEncryptionKeysDeleteEncryptionKeysWithHttpInfo(id = id, digest = digest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigEncryptionKeysDeleteEncryptionKeysResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /config/encryption-keys/{id}
     * Remove encryption key
     * Remove encryption key.
     * @param id ID to uniquely identify encryption/decription key
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return ApiResponse<ConfigEncryptionKeysDeleteEncryptionKeysResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configEncryptionKeysDeleteEncryptionKeysWithHttpInfo(id: kotlin.String, digest: kotlin.String?) : ApiResponse<ConfigEncryptionKeysDeleteEncryptionKeysResponse?> {
        val localVariableConfig = configEncryptionKeysDeleteEncryptionKeysRequestConfig(id = id, digest = digest)

        return request<Unit, ConfigEncryptionKeysDeleteEncryptionKeysResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configEncryptionKeysDeleteEncryptionKeys
     *
     * @param id ID to uniquely identify encryption/decription key
     * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @return RequestConfig
     */
    fun configEncryptionKeysDeleteEncryptionKeysRequestConfig(id: kotlin.String, digest: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (digest != null) {
                    put("digest", listOf(digest.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/config/encryption-keys/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /config/encryption-keys
     * List configured encryption keys
     * List configured encryption keys.  Permissions: List configured encryption keys filtered by Sys.Audit privileges
     * @param includeArchived List also keys which have been archived. (optional, default to false)
     * @return ConfigEncryptionKeysGetEncryptionKeysResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun configEncryptionKeysGetEncryptionKeys(includeArchived: kotlin.Boolean? = false) : ConfigEncryptionKeysGetEncryptionKeysResponse {
        val localVarResponse = configEncryptionKeysGetEncryptionKeysWithHttpInfo(includeArchived = includeArchived)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ConfigEncryptionKeysGetEncryptionKeysResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /config/encryption-keys
     * List configured encryption keys
     * List configured encryption keys.  Permissions: List configured encryption keys filtered by Sys.Audit privileges
     * @param includeArchived List also keys which have been archived. (optional, default to false)
     * @return ApiResponse<ConfigEncryptionKeysGetEncryptionKeysResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun configEncryptionKeysGetEncryptionKeysWithHttpInfo(includeArchived: kotlin.Boolean?) : ApiResponse<ConfigEncryptionKeysGetEncryptionKeysResponse?> {
        val localVariableConfig = configEncryptionKeysGetEncryptionKeysRequestConfig(includeArchived = includeArchived)

        return request<Unit, ConfigEncryptionKeysGetEncryptionKeysResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation configEncryptionKeysGetEncryptionKeys
     *
     * @param includeArchived List also keys which have been archived. (optional, default to false)
     * @return RequestConfig
     */
    fun configEncryptionKeysGetEncryptionKeysRequestConfig(includeArchived: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (includeArchived != null) {
                    put("include-archived", listOf(includeArchived.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/config/encryption-keys",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
