/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.NodesSubscriptionCreateSubscriptionRequest
import com.clientapi.pbs.models.NodesSubscriptionCreateSubscriptionResponse
import com.clientapi.pbs.models.NodesSubscriptionDeleteSubscriptionResponse
import com.clientapi.pbs.models.NodesSubscriptionGetSubscriptionResponse
import com.clientapi.pbs.models.NodesSubscriptionUpdateSubscriptionRequest
import com.clientapi.pbs.models.NodesSubscriptionUpdateSubscriptionResponse
import com.clientapi.pbs.models.PbsError

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class NodesSubscriptionApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/subscription
     * Check and update subscription status
     * Check and update subscription status.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionCreateSubscriptionRequest  (optional)
     * @return NodesSubscriptionCreateSubscriptionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesSubscriptionCreateSubscription(node: kotlin.String, nodesSubscriptionCreateSubscriptionRequest: NodesSubscriptionCreateSubscriptionRequest? = null) : NodesSubscriptionCreateSubscriptionResponse {
        val localVarResponse = nodesSubscriptionCreateSubscriptionWithHttpInfo(node = node, nodesSubscriptionCreateSubscriptionRequest = nodesSubscriptionCreateSubscriptionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesSubscriptionCreateSubscriptionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/subscription
     * Check and update subscription status
     * Check and update subscription status.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionCreateSubscriptionRequest  (optional)
     * @return ApiResponse<NodesSubscriptionCreateSubscriptionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesSubscriptionCreateSubscriptionWithHttpInfo(node: kotlin.String, nodesSubscriptionCreateSubscriptionRequest: NodesSubscriptionCreateSubscriptionRequest?) : ApiResponse<NodesSubscriptionCreateSubscriptionResponse?> {
        val localVariableConfig = nodesSubscriptionCreateSubscriptionRequestConfig(node = node, nodesSubscriptionCreateSubscriptionRequest = nodesSubscriptionCreateSubscriptionRequest)

        return request<NodesSubscriptionCreateSubscriptionRequest, NodesSubscriptionCreateSubscriptionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesSubscriptionCreateSubscription
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionCreateSubscriptionRequest  (optional)
     * @return RequestConfig
     */
    fun nodesSubscriptionCreateSubscriptionRequestConfig(node: kotlin.String, nodesSubscriptionCreateSubscriptionRequest: NodesSubscriptionCreateSubscriptionRequest?) : RequestConfig<NodesSubscriptionCreateSubscriptionRequest> {
        val localVariableBody = nodesSubscriptionCreateSubscriptionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/subscription".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/subscription
     * Delete subscription info
     * Delete subscription info.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesSubscriptionDeleteSubscriptionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesSubscriptionDeleteSubscription(node: kotlin.String) : NodesSubscriptionDeleteSubscriptionResponse {
        val localVarResponse = nodesSubscriptionDeleteSubscriptionWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesSubscriptionDeleteSubscriptionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/subscription
     * Delete subscription info
     * Delete subscription info.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesSubscriptionDeleteSubscriptionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesSubscriptionDeleteSubscriptionWithHttpInfo(node: kotlin.String) : ApiResponse<NodesSubscriptionDeleteSubscriptionResponse?> {
        val localVariableConfig = nodesSubscriptionDeleteSubscriptionRequestConfig(node = node)

        return request<Unit, NodesSubscriptionDeleteSubscriptionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesSubscriptionDeleteSubscription
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesSubscriptionDeleteSubscriptionRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/subscription".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/subscription
     * Read subscription info
     * Read subscription info.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesSubscriptionGetSubscriptionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesSubscriptionGetSubscription(node: kotlin.String) : NodesSubscriptionGetSubscriptionResponse {
        val localVarResponse = nodesSubscriptionGetSubscriptionWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesSubscriptionGetSubscriptionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/subscription
     * Read subscription info
     * Read subscription info.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesSubscriptionGetSubscriptionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesSubscriptionGetSubscriptionWithHttpInfo(node: kotlin.String) : ApiResponse<NodesSubscriptionGetSubscriptionResponse?> {
        val localVariableConfig = nodesSubscriptionGetSubscriptionRequestConfig(node = node)

        return request<Unit, NodesSubscriptionGetSubscriptionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesSubscriptionGetSubscription
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesSubscriptionGetSubscriptionRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/subscription".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/subscription
     * Set a subscription key and check it
     * Set a subscription key and check it.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionUpdateSubscriptionRequest 
     * @return NodesSubscriptionUpdateSubscriptionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesSubscriptionUpdateSubscription(node: kotlin.String, nodesSubscriptionUpdateSubscriptionRequest: NodesSubscriptionUpdateSubscriptionRequest) : NodesSubscriptionUpdateSubscriptionResponse {
        val localVarResponse = nodesSubscriptionUpdateSubscriptionWithHttpInfo(node = node, nodesSubscriptionUpdateSubscriptionRequest = nodesSubscriptionUpdateSubscriptionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesSubscriptionUpdateSubscriptionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/subscription
     * Set a subscription key and check it
     * Set a subscription key and check it.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionUpdateSubscriptionRequest 
     * @return ApiResponse<NodesSubscriptionUpdateSubscriptionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesSubscriptionUpdateSubscriptionWithHttpInfo(node: kotlin.String, nodesSubscriptionUpdateSubscriptionRequest: NodesSubscriptionUpdateSubscriptionRequest) : ApiResponse<NodesSubscriptionUpdateSubscriptionResponse?> {
        val localVariableConfig = nodesSubscriptionUpdateSubscriptionRequestConfig(node = node, nodesSubscriptionUpdateSubscriptionRequest = nodesSubscriptionUpdateSubscriptionRequest)

        return request<NodesSubscriptionUpdateSubscriptionRequest, NodesSubscriptionUpdateSubscriptionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesSubscriptionUpdateSubscription
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesSubscriptionUpdateSubscriptionRequest 
     * @return RequestConfig
     */
    fun nodesSubscriptionUpdateSubscriptionRequestConfig(node: kotlin.String, nodesSubscriptionUpdateSubscriptionRequest: NodesSubscriptionUpdateSubscriptionRequest) : RequestConfig<NodesSubscriptionUpdateSubscriptionRequest> {
        val localVariableBody = nodesSubscriptionUpdateSubscriptionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/subscription".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
