/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.NodesDisksCreateDirectoryRequest
import com.clientapi.pbs.models.NodesDisksCreateDirectoryResponse
import com.clientapi.pbs.models.NodesDisksCreateInitgptRequest
import com.clientapi.pbs.models.NodesDisksCreateInitgptResponse
import com.clientapi.pbs.models.NodesDisksCreateZfsRequest
import com.clientapi.pbs.models.NodesDisksCreateZfsResponse
import com.clientapi.pbs.models.NodesDisksDeleteDirectoryResponse
import com.clientapi.pbs.models.NodesDisksGetDirectoryResponse
import com.clientapi.pbs.models.NodesDisksGetDisksResponse
import com.clientapi.pbs.models.NodesDisksGetListResponse
import com.clientapi.pbs.models.NodesDisksGetNodesByNodeDisksZfsByNameResponse
import com.clientapi.pbs.models.NodesDisksGetSmartResponse
import com.clientapi.pbs.models.NodesDisksGetZfsResponse
import com.clientapi.pbs.models.NodesDisksUpdateWipediskRequest
import com.clientapi.pbs.models.NodesDisksUpdateWipediskResponse
import com.clientapi.pbs.models.PbsError
import com.clientapi.pbs.models.PbsUsageTypeEnum

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class NodesDisksApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /nodes/{node}/disks/directory
     * Create a Filesystem on an unused disk
     * Create a Filesystem on an unused disk. Will be mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateDirectoryRequest 
     * @return NodesDisksCreateDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateDirectory(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : NodesDisksCreateDirectoryResponse {
        val localVarResponse = nodesDisksCreateDirectoryWithHttpInfo(node = node, nodesDisksCreateDirectoryRequest = nodesDisksCreateDirectoryRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/directory
     * Create a Filesystem on an unused disk
     * Create a Filesystem on an unused disk. Will be mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateDirectoryRequest 
     * @return ApiResponse<NodesDisksCreateDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateDirectoryWithHttpInfo(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : ApiResponse<NodesDisksCreateDirectoryResponse?> {
        val localVariableConfig = nodesDisksCreateDirectoryRequestConfig(node = node, nodesDisksCreateDirectoryRequest = nodesDisksCreateDirectoryRequest)

        return request<NodesDisksCreateDirectoryRequest, NodesDisksCreateDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateDirectory
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateDirectoryRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateDirectoryRequestConfig(node: kotlin.String, nodesDisksCreateDirectoryRequest: NodesDisksCreateDirectoryRequest) : RequestConfig<NodesDisksCreateDirectoryRequest> {
        val localVariableBody = nodesDisksCreateDirectoryRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/directory".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/initgpt
     * Initialize empty Disk with GPT
     * Initialize empty Disk with GPT
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateInitgptRequest 
     * @return NodesDisksCreateInitgptResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateInitgpt(node: kotlin.String, nodesDisksCreateInitgptRequest: NodesDisksCreateInitgptRequest) : NodesDisksCreateInitgptResponse {
        val localVarResponse = nodesDisksCreateInitgptWithHttpInfo(node = node, nodesDisksCreateInitgptRequest = nodesDisksCreateInitgptRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateInitgptResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/initgpt
     * Initialize empty Disk with GPT
     * Initialize empty Disk with GPT
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateInitgptRequest 
     * @return ApiResponse<NodesDisksCreateInitgptResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateInitgptWithHttpInfo(node: kotlin.String, nodesDisksCreateInitgptRequest: NodesDisksCreateInitgptRequest) : ApiResponse<NodesDisksCreateInitgptResponse?> {
        val localVariableConfig = nodesDisksCreateInitgptRequestConfig(node = node, nodesDisksCreateInitgptRequest = nodesDisksCreateInitgptRequest)

        return request<NodesDisksCreateInitgptRequest, NodesDisksCreateInitgptResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateInitgpt
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateInitgptRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateInitgptRequestConfig(node: kotlin.String, nodesDisksCreateInitgptRequest: NodesDisksCreateInitgptRequest) : RequestConfig<NodesDisksCreateInitgptRequest> {
        val localVariableBody = nodesDisksCreateInitgptRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/initgpt".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /nodes/{node}/disks/zfs
     * Create a new ZFS pool
     * Create a new ZFS pool. Will be mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateZfsRequest 
     * @return NodesDisksCreateZfsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksCreateZfs(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : NodesDisksCreateZfsResponse {
        val localVarResponse = nodesDisksCreateZfsWithHttpInfo(node = node, nodesDisksCreateZfsRequest = nodesDisksCreateZfsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksCreateZfsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /nodes/{node}/disks/zfs
     * Create a new ZFS pool
     * Create a new ZFS pool. Will be mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateZfsRequest 
     * @return ApiResponse<NodesDisksCreateZfsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksCreateZfsWithHttpInfo(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : ApiResponse<NodesDisksCreateZfsResponse?> {
        val localVariableConfig = nodesDisksCreateZfsRequestConfig(node = node, nodesDisksCreateZfsRequest = nodesDisksCreateZfsRequest)

        return request<NodesDisksCreateZfsRequest, NodesDisksCreateZfsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksCreateZfs
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksCreateZfsRequest 
     * @return RequestConfig
     */
    fun nodesDisksCreateZfsRequestConfig(node: kotlin.String, nodesDisksCreateZfsRequest: NodesDisksCreateZfsRequest) : RequestConfig<NodesDisksCreateZfsRequest> {
        val localVariableBody = nodesDisksCreateZfsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/nodes/{node}/disks/zfs".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /nodes/{node}/disks/directory/{name}
     * Remove a Filesystem mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;
     * Remove a Filesystem mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param name Datastore name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesDisksDeleteDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksDeleteDirectory(name: kotlin.String, node: kotlin.String) : NodesDisksDeleteDirectoryResponse {
        val localVarResponse = nodesDisksDeleteDirectoryWithHttpInfo(name = name, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksDeleteDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /nodes/{node}/disks/directory/{name}
     * Remove a Filesystem mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;
     * Remove a Filesystem mounted under &#x60;/mnt/datastore/&lt;name&gt;&#x60;.
     * @param name Datastore name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesDisksDeleteDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksDeleteDirectoryWithHttpInfo(name: kotlin.String, node: kotlin.String) : ApiResponse<NodesDisksDeleteDirectoryResponse?> {
        val localVariableConfig = nodesDisksDeleteDirectoryRequestConfig(name = name, node = node)

        return request<Unit, NodesDisksDeleteDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksDeleteDirectory
     *
     * @param name Datastore name.
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesDisksDeleteDirectoryRequestConfig(name: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/nodes/{node}/disks/directory/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/directory
     * List systemd datastore mount units
     * List systemd datastore mount units.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesDisksGetDirectoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetDirectory(node: kotlin.String) : NodesDisksGetDirectoryResponse {
        val localVarResponse = nodesDisksGetDirectoryWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetDirectoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/directory
     * List systemd datastore mount units
     * List systemd datastore mount units.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesDisksGetDirectoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetDirectoryWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetDirectoryResponse?> {
        val localVariableConfig = nodesDisksGetDirectoryRequestConfig(node = node)

        return request<Unit, NodesDisksGetDirectoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetDirectory
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesDisksGetDirectoryRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/directory".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks
     * Directory index
     * Directory index.
     * @param node 
     * @return NodesDisksGetDisksResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetDisks(node: kotlin.String) : NodesDisksGetDisksResponse {
        val localVarResponse = nodesDisksGetDisksWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetDisksResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks
     * Directory index
     * Directory index.
     * @param node 
     * @return ApiResponse<NodesDisksGetDisksResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetDisksWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetDisksResponse?> {
        val localVariableConfig = nodesDisksGetDisksRequestConfig(node = node)

        return request<Unit, NodesDisksGetDisksResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetDisks
     *
     * @param node 
     * @return RequestConfig
     */
    fun nodesDisksGetDisksRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/list
     * List local disks
     * List local disks
     * @param node Node name (or &#39;localhost&#39;)
     * @param includePartitions Include partitions. (optional, default to false)
     * @param skipsmart Skip smart checks. (optional, default to false)
     * @param usageType What a block device (disk) is used for. (optional)
     * @return NodesDisksGetListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetList(node: kotlin.String, includePartitions: kotlin.Boolean? = false, skipsmart: kotlin.Boolean? = false, usageType: PbsUsageTypeEnum? = null) : NodesDisksGetListResponse {
        val localVarResponse = nodesDisksGetListWithHttpInfo(node = node, includePartitions = includePartitions, skipsmart = skipsmart, usageType = usageType)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/list
     * List local disks
     * List local disks
     * @param node Node name (or &#39;localhost&#39;)
     * @param includePartitions Include partitions. (optional, default to false)
     * @param skipsmart Skip smart checks. (optional, default to false)
     * @param usageType What a block device (disk) is used for. (optional)
     * @return ApiResponse<NodesDisksGetListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetListWithHttpInfo(node: kotlin.String, includePartitions: kotlin.Boolean?, skipsmart: kotlin.Boolean?, usageType: PbsUsageTypeEnum?) : ApiResponse<NodesDisksGetListResponse?> {
        val localVariableConfig = nodesDisksGetListRequestConfig(node = node, includePartitions = includePartitions, skipsmart = skipsmart, usageType = usageType)

        return request<Unit, NodesDisksGetListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetList
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param includePartitions Include partitions. (optional, default to false)
     * @param skipsmart Skip smart checks. (optional, default to false)
     * @param usageType What a block device (disk) is used for. (optional)
     * @return RequestConfig
     */
    fun nodesDisksGetListRequestConfig(node: kotlin.String, includePartitions: kotlin.Boolean?, skipsmart: kotlin.Boolean?, usageType: PbsUsageTypeEnum?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (includePartitions != null) {
                    put("include-partitions", listOf(includePartitions.toString()))
                }
                if (skipsmart != null) {
                    put("skipsmart", listOf(skipsmart.toString()))
                }
                if (usageType != null) {
                    put("usage-type", listOf(usageType.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/list".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/zfs/{name}
     * Get zpool status details
     * Get zpool status details.
     * @param name ZFS Pool Name
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesDisksGetNodesByNodeDisksZfsByNameResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetNodesByNodeDisksZfsByName(name: kotlin.String, node: kotlin.String) : NodesDisksGetNodesByNodeDisksZfsByNameResponse {
        val localVarResponse = nodesDisksGetNodesByNodeDisksZfsByNameWithHttpInfo(name = name, node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetNodesByNodeDisksZfsByNameResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/zfs/{name}
     * Get zpool status details
     * Get zpool status details.
     * @param name ZFS Pool Name
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesDisksGetNodesByNodeDisksZfsByNameResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetNodesByNodeDisksZfsByNameWithHttpInfo(name: kotlin.String, node: kotlin.String) : ApiResponse<NodesDisksGetNodesByNodeDisksZfsByNameResponse?> {
        val localVariableConfig = nodesDisksGetNodesByNodeDisksZfsByNameRequestConfig(name = name, node = node)

        return request<Unit, NodesDisksGetNodesByNodeDisksZfsByNameResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetNodesByNodeDisksZfsByName
     *
     * @param name ZFS Pool Name
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesDisksGetNodesByNodeDisksZfsByNameRequestConfig(name: kotlin.String, node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/zfs/{name}".replace("{"+"name"+"}", encodeURIComponent(name.toString())).replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/smart
     * Get SMART attributes and health of a disk
     * Get SMART attributes and health of a disk.
     * @param node Node name (or &#39;localhost&#39;)
     * @param disk Block device name (/sys/block/&lt;name&gt;).
     * @param healthonly If true returns only the health status. (optional)
     * @return NodesDisksGetSmartResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetSmart(node: kotlin.String, disk: kotlin.String, healthonly: kotlin.Boolean? = null) : NodesDisksGetSmartResponse {
        val localVarResponse = nodesDisksGetSmartWithHttpInfo(node = node, disk = disk, healthonly = healthonly)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetSmartResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/smart
     * Get SMART attributes and health of a disk
     * Get SMART attributes and health of a disk.
     * @param node Node name (or &#39;localhost&#39;)
     * @param disk Block device name (/sys/block/&lt;name&gt;).
     * @param healthonly If true returns only the health status. (optional)
     * @return ApiResponse<NodesDisksGetSmartResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetSmartWithHttpInfo(node: kotlin.String, disk: kotlin.String, healthonly: kotlin.Boolean?) : ApiResponse<NodesDisksGetSmartResponse?> {
        val localVariableConfig = nodesDisksGetSmartRequestConfig(node = node, disk = disk, healthonly = healthonly)

        return request<Unit, NodesDisksGetSmartResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetSmart
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param disk Block device name (/sys/block/&lt;name&gt;).
     * @param healthonly If true returns only the health status. (optional)
     * @return RequestConfig
     */
    fun nodesDisksGetSmartRequestConfig(node: kotlin.String, disk: kotlin.String, healthonly: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("disk", listOf(disk.toString()))
                if (healthonly != null) {
                    put("healthonly", listOf(healthonly.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/smart".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /nodes/{node}/disks/zfs
     * List zfs pools
     * List zfs pools.
     * @param node Node name (or &#39;localhost&#39;)
     * @return NodesDisksGetZfsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksGetZfs(node: kotlin.String) : NodesDisksGetZfsResponse {
        val localVarResponse = nodesDisksGetZfsWithHttpInfo(node = node)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksGetZfsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /nodes/{node}/disks/zfs
     * List zfs pools
     * List zfs pools.
     * @param node Node name (or &#39;localhost&#39;)
     * @return ApiResponse<NodesDisksGetZfsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksGetZfsWithHttpInfo(node: kotlin.String) : ApiResponse<NodesDisksGetZfsResponse?> {
        val localVariableConfig = nodesDisksGetZfsRequestConfig(node = node)

        return request<Unit, NodesDisksGetZfsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksGetZfs
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @return RequestConfig
     */
    fun nodesDisksGetZfsRequestConfig(node: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/nodes/{node}/disks/zfs".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /nodes/{node}/disks/wipedisk
     * wipe disk
     * wipe disk
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksUpdateWipediskRequest 
     * @return NodesDisksUpdateWipediskResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nodesDisksUpdateWipedisk(node: kotlin.String, nodesDisksUpdateWipediskRequest: NodesDisksUpdateWipediskRequest) : NodesDisksUpdateWipediskResponse {
        val localVarResponse = nodesDisksUpdateWipediskWithHttpInfo(node = node, nodesDisksUpdateWipediskRequest = nodesDisksUpdateWipediskRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NodesDisksUpdateWipediskResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /nodes/{node}/disks/wipedisk
     * wipe disk
     * wipe disk
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksUpdateWipediskRequest 
     * @return ApiResponse<NodesDisksUpdateWipediskResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun nodesDisksUpdateWipediskWithHttpInfo(node: kotlin.String, nodesDisksUpdateWipediskRequest: NodesDisksUpdateWipediskRequest) : ApiResponse<NodesDisksUpdateWipediskResponse?> {
        val localVariableConfig = nodesDisksUpdateWipediskRequestConfig(node = node, nodesDisksUpdateWipediskRequest = nodesDisksUpdateWipediskRequest)

        return request<NodesDisksUpdateWipediskRequest, NodesDisksUpdateWipediskResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation nodesDisksUpdateWipedisk
     *
     * @param node Node name (or &#39;localhost&#39;)
     * @param nodesDisksUpdateWipediskRequest 
     * @return RequestConfig
     */
    fun nodesDisksUpdateWipediskRequestConfig(node: kotlin.String, nodesDisksUpdateWipediskRequest: NodesDisksUpdateWipediskRequest) : RequestConfig<NodesDisksUpdateWipediskRequest> {
        val localVariableBody = nodesDisksUpdateWipediskRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/nodes/{node}/disks/wipedisk".replace("{"+"node"+"}", encodeURIComponent(node.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
