/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.clientapi.pbs.models.PbsError
import com.clientapi.pbs.models.PullCreatePullRequest
import com.clientapi.pbs.models.PullCreatePullResponse

import com.squareup.moshi.Json

import com.clientapi.pbs.infrastructure.ApiClient
import com.clientapi.pbs.infrastructure.ApiResponse
import com.clientapi.pbs.infrastructure.ClientException
import com.clientapi.pbs.infrastructure.ClientError
import com.clientapi.pbs.infrastructure.ServerException
import com.clientapi.pbs.infrastructure.ServerError
import com.clientapi.pbs.infrastructure.MultiValueMap
import com.clientapi.pbs.infrastructure.PartConfig
import com.clientapi.pbs.infrastructure.RequestConfig
import com.clientapi.pbs.infrastructure.RequestMethod
import com.clientapi.pbs.infrastructure.ResponseType
import com.clientapi.pbs.infrastructure.Success
import com.clientapi.pbs.infrastructure.toMultiValue

open class PullApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://localhost:8007/api2/json")
        }
    }

    /**
     * POST /pull
     * Sync store from other repository
     * Sync store from other repository  Permissions: The user needs Datastore.Backup privilege on &#39;/datastore/{store}&#39;, and needs to own the backup group. Remote.Read is required on &#39;/remote/{remote}/{remote-store}&#39;. The delete flag additionally requires the Datastore.Prune privilege on &#39;/datastore/{store}&#39;.
     * @param pullCreatePullRequest 
     * @return PullCreatePullResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun pullCreatePull(pullCreatePullRequest: PullCreatePullRequest) : PullCreatePullResponse {
        val localVarResponse = pullCreatePullWithHttpInfo(pullCreatePullRequest = pullCreatePullRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PullCreatePullResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /pull
     * Sync store from other repository
     * Sync store from other repository  Permissions: The user needs Datastore.Backup privilege on &#39;/datastore/{store}&#39;, and needs to own the backup group. Remote.Read is required on &#39;/remote/{remote}/{remote-store}&#39;. The delete flag additionally requires the Datastore.Prune privilege on &#39;/datastore/{store}&#39;.
     * @param pullCreatePullRequest 
     * @return ApiResponse<PullCreatePullResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun pullCreatePullWithHttpInfo(pullCreatePullRequest: PullCreatePullRequest) : ApiResponse<PullCreatePullResponse?> {
        val localVariableConfig = pullCreatePullRequestConfig(pullCreatePullRequest = pullCreatePullRequest)

        return request<PullCreatePullRequest, PullCreatePullResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation pullCreatePull
     *
     * @param pullCreatePullRequest 
     * @return RequestConfig
     */
    fun pullCreatePullRequestConfig(pullCreatePullRequest: PullCreatePullRequest) : RequestConfig<PullCreatePullRequest> {
        val localVariableBody = pullCreatePullRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/pull",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
