/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsAccessAclUgidTypeEnum
import com.clientapi.pbs.models.PbsRoleidEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path Access control path.
 * @param propagate Allow to propagate (inherit) permissions.
 * @param roleid Enum representing roles via their [PRIVILEGES] combination.  Since privileges are implemented as bitflags, each unique combination of privileges maps to a single, unique `u64` value that is used in this enum definition.
 * @param ugid User or Group ID.
 * @param ugidType Type of 'ugid' property.
 */


data class AccessAclGetAclResponseDataInner (

    /* Access control path. */
    @Json(name = "path")
    val path: kotlin.String,

    /* Allow to propagate (inherit) permissions. */
    @Json(name = "propagate")
    val propagate: kotlin.Boolean = 1,

    /* Enum representing roles via their [PRIVILEGES] combination.  Since privileges are implemented as bitflags, each unique combination of privileges maps to a single, unique `u64` value that is used in this enum definition. */
    @Json(name = "roleid")
    val roleid: PbsRoleidEnum,

    /* User or Group ID. */
    @Json(name = "ugid")
    val ugid: kotlin.String,

    /* Type of 'ugid' property. */
    @Json(name = "ugid_type")
    val ugidType: PbsAccessAclUgidTypeEnum

) {


}

