/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authid Authentication ID
 * @param path Verify ticket, and check if user have access 'privs' on 'path'.
 * @param privs Verify ticket, and check if user have access 'privs' on 'path'.
 * @param vncticket The VNC ticket
 * @param port Port for verifying terminal tickets.
 */


data class AccessCreateVncticketRequest (

    /* Authentication ID */
    @Json(name = "authid")
    val authid: kotlin.String,

    /* Verify ticket, and check if user have access 'privs' on 'path'. */
    @Json(name = "path")
    val path: kotlin.String,

    /* Verify ticket, and check if user have access 'privs' on 'path'. */
    @Json(name = "privs")
    val privs: kotlin.String,

    /* The VNC ticket */
    @Json(name = "vncticket")
    val vncticket: kotlin.String,

    /* Port for verifying terminal tickets. */
    @Json(name = "port")
    val port: kotlin.Int? = null

) {


}

