/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param realm Realm name.
 * @param type type of the realm
 * @param comment Comment.
 * @param default True if it is the default realm
 */


data class AccessDomainsGetDomainsResponseDataInner (

    /* Realm name. */
    @Json(name = "realm")
    val realm: kotlin.String,

    /* type of the realm */
    @Json(name = "type")
    val type: PbsTypeEnum,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* True if it is the default realm */
    @Json(name = "default")
    val default: kotlin.Boolean? = 0

) {


}

