/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsBackendTypeEnum
import com.clientapi.pbs.models.PbsMaintenanceField
import com.clientapi.pbs.models.PbsMountStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param backendType Datastore backend type
 * @param mountStatus Current mounting status of a datastore, useful for removable datastores.
 * @param store Datastore name.
 * @param comment Comment.
 * @param maintenance If the datastore is in maintenance mode, information about it
 */


data class AdminDatastoreGetDatastoreResponseDataInner (

    /* Datastore backend type */
    @Json(name = "backend-type")
    val backendType: PbsBackendTypeEnum,

    /* Current mounting status of a datastore, useful for removable datastores. */
    @Json(name = "mount-status")
    val mountStatus: PbsMountStatusEnum,

    /* Datastore name. */
    @Json(name = "store")
    val store: kotlin.String,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* If the datastore is in maintenance mode, information about it */
    @Json(name = "maintenance")
    val maintenance: PbsMaintenanceField? = null

) {


}

