/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsAdminDatastoreCryptModeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filename Backup archive name.
 * @param cryptMode Defines whether data is encrypted (using an AEAD cipher), only signed, or neither.
 * @param propertySize Archive size (from backup manifest).
 */


data class AdminDatastoreGetFilesResponseDataInner (

    /* Backup archive name. */
    @Json(name = "filename")
    val filename: kotlin.String,

    /* Defines whether data is encrypted (using an AEAD cipher), only signed, or neither. */
    @Json(name = "crypt-mode")
    val cryptMode: PbsAdminDatastoreCryptModeEnum? = null,

    /* Archive size (from backup manifest). */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null

) {


}

