/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.AdminDatastoreGetSnapshotsResponseDataInnerVerification
import com.clientapi.pbs.models.PbsBackupTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param backupId Backup ID.
 * @param backupTime Backup time (Unix epoch.)
 * @param backupType Backup types.
 * @param files List of contained archive files.
 * @param `protected` Protection from prunes
 * @param comment Comment.
 * @param fingerprint Fingerprint of encryption key
 * @param owner Authentication ID
 * @param propertySize Overall snapshot size (sum of all archive sizes).
 * @param verification 
 */


data class AdminDatastoreGetSnapshotsResponseDataInner (

    /* Backup ID. */
    @Json(name = "backup-id")
    val backupId: kotlin.String,

    /* Backup time (Unix epoch.) */
    @Json(name = "backup-time")
    val backupTime: kotlin.Long,

    /* Backup types. */
    @Json(name = "backup-type")
    val backupType: PbsBackupTypeEnum,

    /* List of contained archive files. */
    @Json(name = "files")
    val files: kotlin.collections.List<kotlin.String>,

    /* Protection from prunes */
    @Json(name = "protected")
    val `protected`: kotlin.Boolean,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Fingerprint of encryption key */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null,

    /* Authentication ID */
    @Json(name = "owner")
    val owner: kotlin.String? = null,

    /* Overall snapshot size (sum of all archive sizes). */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null,

    @Json(name = "verification")
    val verification: AdminDatastoreGetSnapshotsResponseDataInnerVerification? = null

) {


}

