/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param digest Chunk digest (SHA256).
 * @param encodedSize Encoded chunk size.
 * @param propertySize Chunk size.
 * @param wid Dynamic writer ID.
 */


data class BackupUpgradeCreateDynamicChunkRequest (

    /* Chunk digest (SHA256). */
    @Json(name = "digest")
    val digest: kotlin.String,

    /* Encoded chunk size. */
    @Json(name = "encoded-size")
    val encodedSize: kotlin.Int,

    /* Chunk size. */
    @Json(name = "size")
    val propertySize: kotlin.Int,

    /* Dynamic writer ID. */
    @Json(name = "wid")
    val wid: kotlin.Int

) {


}

