/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chunkCount Chunk count. This is used to verify that the server got all chunks.
 * @param csum Digest list checksum.
 * @param propertySize File size. This is used to verify that the server got all data.
 * @param wid Dynamic writer ID.
 */


data class BackupUpgradeCreateDynamicCloseRequest (

    /* Chunk count. This is used to verify that the server got all chunks. */
    @Json(name = "chunk-count")
    val chunkCount: kotlin.Long,

    /* Digest list checksum. */
    @Json(name = "csum")
    val csum: kotlin.String,

    /* File size. This is used to verify that the server got all data. */
    @Json(name = "size")
    val propertySize: kotlin.Long,

    /* Dynamic writer ID. */
    @Json(name = "wid")
    val wid: kotlin.Int

) {


}

