/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param archiveName Backup archive name.
 * @param reuseCsum If set, compare last backup's csum and reuse index for incremental backup if it matches.
 * @param propertySize File size.
 */


data class BackupUpgradeCreateFixedIndexRequest (

    /* Backup archive name. */
    @Json(name = "archive-name")
    val archiveName: kotlin.String,

    /* If set, compare last backup's csum and reuse index for incremental backup if it matches. */
    @Json(name = "reuse-csum")
    val reuseCsum: kotlin.String? = null,

    /* File size. */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null

) {


}

