/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsConfigNotificationsInlineEnum5
import com.clientapi.pbs.models.PbsModeModeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param comment Comment.
 * @param delete List of properties to delete.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param disable Disable this matcher.
 * @param invertMatch Invert match of the whole filter.
 * @param matchCalendar List of matched severity levels.
 * @param matchField List of matched metadata fields.
 * @param matchSeverity List of matched severity levels.
 * @param mode The mode in which the results of matches are combined.
 * @param target Targets to notify.
 */


data class ConfigNotificationsUpdateMatchersRequest (

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PbsConfigNotificationsInlineEnum5>? = null,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Disable this matcher. */
    @Json(name = "disable")
    val disable: kotlin.Boolean? = null,

    /* Invert match of the whole filter. */
    @Json(name = "invert-match")
    val invertMatch: kotlin.Boolean? = null,

    /* List of matched severity levels. */
    @Json(name = "match-calendar")
    val matchCalendar: kotlin.collections.List<kotlin.String>? = null,

    /* List of matched metadata fields. */
    @Json(name = "match-field")
    val matchField: kotlin.collections.List<kotlin.String>? = null,

    /* List of matched severity levels. */
    @Json(name = "match-severity")
    val matchSeverity: kotlin.collections.List<kotlin.String>? = null,

    /* The mode in which the results of matches are combined. */
    @Json(name = "mode")
    val mode: PbsModeModeEnum? = null,

    /* Targets to notify. */
    @Json(name = "target")
    val target: kotlin.collections.List<kotlin.String>? = null

) {


}

