/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsKdfEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param created Key creation time
 * @param id ID to uniquely identify encryption/decription key
 * @param kdf Key derivation function for password protected encryption keys.
 * @param modified Key modification time
 * @param archivedAt Timestamp when key was archived (not set if key is active).
 * @param fingerprint X509 certificate fingerprint (sha256).
 * @param hint Password hint
 * @param path Path to key (if stored in a file)
 */


data class ConfigEncryptionKeysGetEncryptionKeysResponseDataInner (

    /* Key creation time */
    @Json(name = "created")
    val created: kotlin.Long,

    /* ID to uniquely identify encryption/decription key */
    @Json(name = "id")
    val id: kotlin.String,

    /* Key derivation function for password protected encryption keys. */
    @Json(name = "kdf")
    val kdf: PbsKdfEnum,

    /* Key modification time */
    @Json(name = "modified")
    val modified: kotlin.Long,

    /* Timestamp when key was archived (not set if key is active). */
    @Json(name = "archived-at")
    val archivedAt: kotlin.Long? = null,

    /* X509 certificate fingerprint (sha256). */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null,

    /* Password hint */
    @Json(name = "hint")
    val hint: kotlin.String? = null,

    /* Path to key (if stored in a file) */
    @Json(name = "path")
    val path: kotlin.String? = null

) {


}

