/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsConfigMediaPoolInlineEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allocation Media set allocation policy ('continue', 'always', or a calendar event).
 * @param comment Comment.
 * @param delete List of properties to delete.
 * @param encrypt Tape encryption key fingerprint (sha256).
 * @param retention Media retention policy ('overwrite', 'keep', or time span).
 * @param template Media set naming template (may contain strftime() time format specifications).
 */


data class ConfigMediaPoolUpdateMediaPoolRequest (

    /* Media set allocation policy ('continue', 'always', or a calendar event). */
    @Json(name = "allocation")
    val allocation: kotlin.String? = null,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* List of properties to delete. */
    @Json(name = "delete")
    val delete: kotlin.collections.List<PbsConfigMediaPoolInlineEnum>? = null,

    /* Tape encryption key fingerprint (sha256). */
    @Json(name = "encrypt")
    val encrypt: kotlin.String? = null,

    /* Media retention policy ('overwrite', 'keep', or time span). */
    @Json(name = "retention")
    val retention: kotlin.String? = null,

    /* Media set naming template (may contain strftime() time format specifications). */
    @Json(name = "template")
    val template: kotlin.String? = null

) {


}

