/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Metrics Server ID.
 * @param url HTTP(s) url with optional port.
 * @param bucket InfluxDB Bucket.
 * @param comment Comment.
 * @param enable Enables or disables the metrics server
 * @param maxBodySize The (optional) maximum body size
 * @param organization InfluxDB Organization.
 * @param token The (optional) API token
 * @param verifyTls If true, the certificate will be validated.
 */


data class ConfigMetricsGetInfluxdbHttpResponseDataInner (

    /* Metrics Server ID. */
    @Json(name = "name")
    val name: kotlin.String,

    /* HTTP(s) url with optional port. */
    @Json(name = "url")
    val url: kotlin.String,

    /* InfluxDB Bucket. */
    @Json(name = "bucket")
    val bucket: kotlin.String? = "proxmox",

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Enables or disables the metrics server */
    @Json(name = "enable")
    val enable: kotlin.Boolean? = true,

    /* The (optional) maximum body size */
    @Json(name = "max-body-size")
    val maxBodySize: kotlin.Long? = 25000000L,

    /* InfluxDB Organization. */
    @Json(name = "organization")
    val organization: kotlin.String? = "proxmox",

    /* The (optional) API token */
    @Json(name = "token")
    val token: kotlin.String? = null,

    /* If true, the certificate will be validated. */
    @Json(name = "verify-tls")
    val verifyTls: kotlin.Boolean? = true

) {


}

