/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Rule ID.
 * @param network Rule applies to Source IPs within this networks
 * @param burstIn Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
 * @param burstOut Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
 * @param comment Comment.
 * @param rateIn Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
 * @param rateOut Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
 * @param timeframe Enable the rule at specific times
 * @param users Rule applies to authenticated API requests of any of these users (overrides IP-only rules)
 */


data class ConfigTrafficControlGetTrafficControlResponseDataInner (

    /* Rule ID. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Rule applies to Source IPs within this networks */
    @Json(name = "network")
    val network: kotlin.collections.List<kotlin.String>,

    /* Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
    @Json(name = "burst-in")
    val burstIn: kotlin.String? = null,

    /* Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
    @Json(name = "burst-out")
    val burstOut: kotlin.String? = null,

    /* Comment. */
    @Json(name = "comment")
    val comment: kotlin.String? = null,

    /* Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
    @Json(name = "rate-in")
    val rateIn: kotlin.String? = null,

    /* Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...). */
    @Json(name = "rate-out")
    val rateOut: kotlin.String? = null,

    /* Enable the rule at specific times */
    @Json(name = "timeframe")
    val timeframe: kotlin.collections.List<kotlin.String>? = null,

    /* Rule applies to authenticated API requests of any of these users (overrides IP-only rules) */
    @Json(name = "users")
    val users: kotlin.collections.List<kotlin.String>? = null

) {


}

