/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsKdfEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hint Password hint.
 * @param newPassword The new password.
 * @param digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
 * @param force Reset the passphrase for a tape key, using the root-only accessible copy.
 * @param kdf Key derivation function for password protected encryption keys.
 * @param password The current password.
 */


data class ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest (

    /* Password hint. */
    @Json(name = "hint")
    val hint: kotlin.String,

    /* The new password. */
    @Json(name = "new-password")
    val newPassword: kotlin.String,

    /* Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. */
    @Json(name = "digest")
    val digest: kotlin.String? = null,

    /* Reset the passphrase for a tape key, using the root-only accessible copy. */
    @Json(name = "force")
    val force: kotlin.Boolean? = false,

    /* Key derivation function for password protected encryption keys. */
    @Json(name = "kdf")
    val kdf: PbsKdfEnum? = null,

    /* The current password. */
    @Json(name = "password")
    val password: kotlin.String? = null

) {


}

