/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: RATE_IN,BURST_IN,RATE_OUT,BURST_OUT,COMMENT,TIMEFRAME,USERS
 */

@JsonClass(generateAdapter = false)
enum class PbsConfigTrafficControlInlineEnum(val value: kotlin.String) {

    @Json(name = "rate-in")
    RATE_IN("rate-in"),

    @Json(name = "burst-in")
    BURST_IN("burst-in"),

    @Json(name = "rate-out")
    RATE_OUT("rate-out"),

    @Json(name = "burst-out")
    BURST_OUT("burst-out"),

    @Json(name = "comment")
    COMMENT("comment"),

    @Json(name = "timeframe")
    TIMEFRAME("timeframe"),

    @Json(name = "users")
    USERS("users");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PbsConfigTrafficControlInlineEnum) "$data" else null

        /**
         * Returns a valid [PbsConfigTrafficControlInlineEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PbsConfigTrafficControlInlineEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

