/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsNotificationModeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param drive Drive Identifier.
 * @param pool Media pool name.
 * @param store Datastore name.
 * @param ejectMedia Eject media upon job completion.
 * @param exportMediaSet Export media set upon job completion.
 * @param forceMediaSet Ignore the allocation policy and start a new media-set.
 * @param groupFilter List of group filters.
 * @param latestOnly Backup latest snapshots only.
 * @param maxDepth How many levels of namespaces should be operated on (0 == no recursion)
 * @param notificationMode Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.
 * @param notifyUser User ID
 * @param ns Namespace.
 * @param workerThreads The number of threads to use for the tape backup job.
 */


data class TapeBackupCreateBackupRequest (

    /* Drive Identifier. */
    @Json(name = "drive")
    val drive: kotlin.String,

    /* Media pool name. */
    @Json(name = "pool")
    val pool: kotlin.String,

    /* Datastore name. */
    @Json(name = "store")
    val store: kotlin.String,

    /* Eject media upon job completion. */
    @Json(name = "eject-media")
    val ejectMedia: kotlin.Boolean? = null,

    /* Export media set upon job completion. */
    @Json(name = "export-media-set")
    val exportMediaSet: kotlin.Boolean? = null,

    /* Ignore the allocation policy and start a new media-set. */
    @Json(name = "force-media-set")
    val forceMediaSet: kotlin.Boolean? = false,

    /* List of group filters. */
    @Json(name = "group-filter")
    val groupFilter: kotlin.collections.List<kotlin.String>? = null,

    /* Backup latest snapshots only. */
    @Json(name = "latest-only")
    val latestOnly: kotlin.Boolean? = null,

    /* How many levels of namespaces should be operated on (0 == no recursion) */
    @Json(name = "max-depth")
    val maxDepth: kotlin.Int? = 7,

    /* Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system. */
    @Json(name = "notification-mode")
    val notificationMode: PbsNotificationModeEnum? = null,

    /* User ID */
    @Json(name = "notify-user")
    val notifyUser: kotlin.String? = null,

    /* Namespace. */
    @Json(name = "ns")
    val ns: kotlin.String? = null,

    /* The number of threads to use for the tape backup job. */
    @Json(name = "worker-threads")
    val workerThreads: kotlin.Int? = 1

) {


}

