/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fast Use fast erase.
 * @param labelText Media Label/Barcode.
 */


data class TapeDriveCreateFormatMediaRequest (

    /* Use fast erase. */
    @Json(name = "fast")
    val fast: kotlin.Boolean? = 1,

    /* Media Label/Barcode. */
    @Json(name = "label-text")
    val labelText: kotlin.String? = null

) {


}

