/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models

import com.clientapi.pbs.models.PbsActivityEnum
import com.clientapi.pbs.models.PbsTapeDriveDensityEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blocksize Block size (0 is variable size)
 * @param bufferMode Drive buffer mode
 * @param compression Compression enabled
 * @param product Product
 * @param revision Revision
 * @param vendor Vendor
 * @param alertFlags Tape Alert Flags
 * @param blockNumber Current block number
 * @param bytesRead Total Bytes Read in Medium Life
 * @param bytesWritten Total Bytes Written in Medium Life
 * @param density The density of a tape medium, derived from the LTO version.
 * @param driveActivity The DT Device Activity from DT Device Status LP page
 * @param fileNumber Current file number
 * @param manufactured Medium Manufacture Date (epoch)
 * @param mediumPasses Count of the total number of times the medium has passed over the head.
 * @param mediumWearout Estimated tape wearout factor (assuming max. 16000 end-to-end passes)
 * @param volumeMounts Number of mounts for the current volume (i.e., Thread Count)
 * @param writeProtect Media is write protected
 */


data class TapeDriveGetStatusResponseData (

    /* Block size (0 is variable size) */
    @Json(name = "blocksize")
    val blocksize: kotlin.Int,

    /* Drive buffer mode */
    @Json(name = "buffer-mode")
    val bufferMode: kotlin.Int,

    /* Compression enabled */
    @Json(name = "compression")
    val compression: kotlin.Boolean,

    /* Product */
    @Json(name = "product")
    val product: kotlin.String,

    /* Revision */
    @Json(name = "revision")
    val revision: kotlin.String,

    /* Vendor */
    @Json(name = "vendor")
    val vendor: kotlin.String,

    /* Tape Alert Flags */
    @Json(name = "alert-flags")
    val alertFlags: kotlin.String? = null,

    /* Current block number */
    @Json(name = "block-number")
    val blockNumber: kotlin.Long? = null,

    /* Total Bytes Read in Medium Life */
    @Json(name = "bytes-read")
    val bytesRead: kotlin.Long? = null,

    /* Total Bytes Written in Medium Life */
    @Json(name = "bytes-written")
    val bytesWritten: kotlin.Long? = null,

    /* The density of a tape medium, derived from the LTO version. */
    @Json(name = "density")
    val density: PbsTapeDriveDensityEnum? = null,

    /* The DT Device Activity from DT Device Status LP page */
    @Json(name = "drive-activity")
    val driveActivity: PbsActivityEnum? = null,

    /* Current file number */
    @Json(name = "file-number")
    val fileNumber: kotlin.Long? = null,

    /* Medium Manufacture Date (epoch) */
    @Json(name = "manufactured")
    val manufactured: kotlin.Long? = null,

    /* Count of the total number of times the medium has passed over the head. */
    @Json(name = "medium-passes")
    val mediumPasses: kotlin.Long? = null,

    /* Estimated tape wearout factor (assuming max. 16000 end-to-end passes) */
    @Json(name = "medium-wearout")
    val mediumWearout: java.math.BigDecimal? = null,

    /* Number of mounts for the current volume (i.e., Thread Count) */
    @Json(name = "volume-mounts")
    val volumeMounts: kotlin.Long? = null,

    /* Media is write protected */
    @Json(name = "write-protect")
    val writeProtect: kotlin.Boolean? = null

) {


}

