/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clientapi.pbs.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param release Version release
 * @param repoid Version repository id
 * @param version Version 'major.minor'
 */


data class VersionGetVersionResponseData (

    /* Version release */
    @Json(name = "release")
    val release: kotlin.String,

    /* Version repository id */
    @Json(name = "repoid")
    val repoid: kotlin.String,

    /* Version 'major.minor' */
    @Json(name = "version")
    val version: kotlin.String

) {


}

